// Code generated by rubix-sdk codegen. DO NOT EDIT.
package pages_widgets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PagesWidgetsClient struct {
	c *client.Client
}

func NewPagesWidgetsClient(c *client.Client) *PagesWidgetsClient {
	return &PagesWidgetsClient{c: c}
}


// Attach POST /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/attach
func (rc *PagesWidgetsClient) Attach(orgId string, deviceId string, pageId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/attach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Detach DELETE /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/detach
func (rc *PagesWidgetsClient) Detach(orgId string, deviceId string, pageId string, widgetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/detach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets
func (rc *PagesWidgetsClient) List(orgId string, deviceId string, pageId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Reorder PUT /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/reorder
func (rc *PagesWidgetsClient) Reorder(orgId string, deviceId string, pageId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/reorder")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateOverrides PATCH /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/overrides
func (rc *PagesWidgetsClient) UpdateOverrides(orgId string, deviceId string, pageId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/widgets/{widgetId}/overrides")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

