// Code generated by rubix-sdk codegen. DO NOT EDIT.
package db_tables

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DbTablesClient struct {
	c *client.Client
}

func NewDbTablesClient(c *client.Client) *DbTablesClient {
	return &DbTablesClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/db/tables
func (rc *DbTablesClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/db/tables")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/db/tables/{tableName}
func (rc *DbTablesClient) Get(orgId string, deviceId string, tableName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tableName": tableName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/db/tables/{tableName}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListRows GET /orgs/{orgId}/devices/{deviceId}/db/tables/{tableName}/rows
func (rc *DbTablesClient) ListRows(orgId string, deviceId string, tableName string, limit int, offset int, orderBy string, orderDir string, filter_field string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tableName": tableName,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	req.SetQueryParam("orderBy", orderBy)
	req.SetQueryParam("orderDir", orderDir)
	req.SetQueryParam("filter[field]", filter_field)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/db/tables/{tableName}/rows")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListPluginTables GET /orgs/{orgId}/devices/{deviceId}/db/plugins/{pluginId}/tables
func (rc *DbTablesClient) ListPluginTables(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/db/plugins/{pluginId}/tables")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

