// Code generated by rubix-sdk codegen. DO NOT EDIT.
package network_devices

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NetworkDevicesClient struct {
	c *client.Client
}

func NewNetworkDevicesClient(c *client.Client) *NetworkDevicesClient {
	return &NetworkDevicesClient{c: c}
}


// AddNetworkDevice POST /orgs/{orgId}/devices/{deviceId}/network-devices
func (rc *NetworkDevicesClient) AddNetworkDevice(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/network-devices")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemoveNetworkDevice DELETE /orgs/{orgId}/devices/{deviceId}/network-devices/{networkDeviceId}
func (rc *NetworkDevicesClient) RemoveNetworkDevice(orgId string, deviceId string, networkDeviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"networkDeviceId": networkDeviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/network-devices/{networkDeviceId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListNetworkDevices GET /orgs/{orgId}/devices/{deviceId}/network-devices
func (rc *NetworkDevicesClient) ListNetworkDevices(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/network-devices")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetNetworkDevice GET /orgs/{orgId}/devices/{deviceId}/network-devices/{networkDeviceId}
func (rc *NetworkDevicesClient) GetNetworkDevice(orgId string, deviceId string, networkDeviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"networkDeviceId": networkDeviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/network-devices/{networkDeviceId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListNetworkExposedPorts GET /orgs/{orgId}/devices/{deviceId}/network-exposed-ports
func (rc *NetworkDevicesClient) ListNetworkExposedPorts(orgId string, deviceId string, network string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("network", network)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/network-exposed-ports")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

