// Code generated by rubix-sdk codegen. DO NOT EDIT.
package client

import (
	"github.com/go-resty/resty/v2"
)

type Client struct {
	R      *resty.Client
	Prefix string
}

func NewClient(baseURL string) *Client {
	r := resty.New().SetBaseURL(baseURL)
	return &Client{
		R:      r,
		Prefix: "/api/v1",
	}
}

type Option func(*resty.Request)

// WithQueryParam adds a query parameter
func WithQueryParam(key, value string) Option {
	return func(r *resty.Request) {
		r.SetQueryParam(key, value)
	}
}

// WithHeader adds a header
func WithHeader(key, value string) Option {
	return func(r *resty.Request) {
		r.SetHeader(key, value)
	}
}

// WithToken sets a bearer auth token
func WithToken(token string) Option {
	return func(r *resty.Request) {
		r.SetAuthToken(token)
	}
}
