// Code generated by rubix-sdk codegen. DO NOT EDIT.
package histories

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type HistoriesClient struct {
	c *client.Client
}

func NewHistoriesClient(c *client.Client) *HistoriesClient {
	return &HistoriesClient{c: c}
}


// ListEnabledNodes GET /orgs/{orgId}/devices/{deviceId}/histories/nodes
func (rc *HistoriesClient) ListEnabledNodes(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/nodes")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetNodePorts GET /orgs/{orgId}/devices/{deviceId}/histories/nodes/{nodeId}/ports
func (rc *HistoriesClient) GetNodePorts(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/nodes/{nodeId}/ports")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetStats GET /orgs/{orgId}/devices/{deviceId}/histories/stats
func (rc *HistoriesClient) GetStats(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/stats")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortSamples GET /orgs/{orgId}/devices/{deviceId}/histories/port-samples
func (rc *HistoriesClient) PortSamples(orgId string, deviceId string, nodeId string, portHandle string, limit int, withOverride bool, withMeta bool, withAlarms bool, alarmWindow int, withInsights bool, insightWindow int, timezone string, dateFormat string, dateFormatCustom string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("nodeId", nodeId)
	req.SetQueryParam("portHandle", portHandle)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("withOverride", strconv.FormatBool(withOverride))
	req.SetQueryParam("withMeta", strconv.FormatBool(withMeta))
	req.SetQueryParam("withAlarms", strconv.FormatBool(withAlarms))
	req.SetQueryParam("alarmWindow", strconv.Itoa(alarmWindow))
	req.SetQueryParam("withInsights", strconv.FormatBool(withInsights))
	req.SetQueryParam("insightWindow", strconv.Itoa(insightWindow))
	req.SetQueryParam("timezone", timezone)
	req.SetQueryParam("dateFormat", dateFormat)
	req.SetQueryParam("dateFormatCustom", dateFormatCustom)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/port-samples")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListEnabledPorts GET /orgs/{orgId}/devices/{deviceId}/histories/ports
func (rc *HistoriesClient) ListEnabledPorts(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/ports")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetPortConfig GET /orgs/{orgId}/devices/{deviceId}/histories/ports/{nodeId}/{portId}
func (rc *HistoriesClient) GetPortConfig(orgId string, deviceId string, nodeId string, portId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/ports/{nodeId}/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdatePortConfig PUT /orgs/{orgId}/devices/{deviceId}/histories/ports/{nodeId}/{portId}
func (rc *HistoriesClient) UpdatePortConfig(orgId string, deviceId string, nodeId string, portId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/ports/{nodeId}/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Diagnostics GET /orgs/{orgId}/devices/{deviceId}/histories/diagnostics
func (rc *HistoriesClient) Diagnostics(orgId string, deviceId string, nodeId string, portHandle string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("nodeId", nodeId)
	req.SetQueryParam("portHandle", portHandle)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/diagnostics")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// All GET /orgs/{orgId}/devices/{deviceId}/histories/all
func (rc *HistoriesClient) All(orgId string, deviceId string, limit int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/histories/all")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

