// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs_system

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsSystemClient struct {
	c *client.Client
}

func NewDocsSystemClient(c *client.Client) *DocsSystemClient {
	return &DocsSystemClient{c: c}
}


// GetManifest GET /orgs/{orgId}/devices/{deviceId}/docs/system/manifest
func (rc *DocsSystemClient) GetManifest(orgId string, deviceId string, rubixVersion string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("rubixVersion", rubixVersion)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/system/manifest")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetPage GET /orgs/{orgId}/devices/{deviceId}/docs/system/{section}/{page}
func (rc *DocsSystemClient) GetPage(orgId string, deviceId string, section string, page string, rubixVersion string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"section": section,
		"page": page,
		
	})
	

	// Set query params
	req.SetQueryParam("rubixVersion", rubixVersion)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/system/{section}/{page}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListVersions GET /orgs/{orgId}/devices/{deviceId}/docs/system/versions
func (rc *DocsSystemClient) ListVersions(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/system/versions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

