// Code generated by rubix-sdk codegen. DO NOT EDIT.
package meta

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type MetaClient struct {
	c *client.Client
}

func NewMetaClient(c *client.Client) *MetaClient {
	return &MetaClient{c: c}
}


// Timezones GET /orgs/{orgId}/devices/{deviceId}/meta/timezones
func (rc *MetaClient) Timezones(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/meta/timezones")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Units GET /orgs/{orgId}/devices/{deviceId}/meta/units
func (rc *MetaClient) Units(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/meta/units")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

