// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nodes_relationships

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodesRelationshipsClient struct {
	c *client.Client
}

func NewNodesRelationshipsClient(c *client.Client) *NodesRelationshipsClient {
	return &NodesRelationshipsClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/relationships
func (rc *NodesRelationshipsClient) Get(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/relationships")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

