// Code generated by rubix-sdk codegen. DO NOT EDIT.
package public_device

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PublicDeviceClient struct {
	c *client.Client
}

func NewPublicDeviceClient(c *client.Client) *PublicDeviceClient {
	return &PublicDeviceClient{c: c}
}


// Register POST /public/device/register
func (rc *PublicDeviceClient) Register(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/public/device/register")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Status GET /public/device/status/{serialNumber}
func (rc *PublicDeviceClient) Status(serialNumber string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"serialNumber": serialNumber,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/public/device/status/{serialNumber}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

