// Code generated by rubix-sdk codegen. DO NOT EDIT.
package admin

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type AdminClient struct {
	c *client.Client
}

func NewAdminClient(c *client.Client) *AdminClient {
	return &AdminClient{c: c}
}


// DisableOrg POST /admin/orgs/{orgId}/disable
func (rc *AdminClient) DisableOrg(orgId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/admin/orgs/{orgId}/disable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// EnableOrg POST /admin/orgs/{orgId}/enable
func (rc *AdminClient) EnableOrg(orgId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/admin/orgs/{orgId}/enable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetOrgStatus GET /admin/orgs/{orgId}/status
func (rc *AdminClient) GetOrgStatus(orgId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/admin/orgs/{orgId}/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

