// Code generated by rubix-sdk codegen. DO NOT EDIT.
package pages_querymap

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PagesQueryMapClient struct {
	c *client.Client
}

func NewPagesQueryMapClient(c *client.Client) *PagesQueryMapClient {
	return &PagesQueryMapClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/pages/{pageId}/query-map
func (rc *PagesQueryMapClient) Get(orgId string, deviceId string, pageId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pageId": pageId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/pages/{pageId}/query-map")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

