// Code generated by rubix-sdk codegen. DO NOT EDIT.
package preferences

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PreferencesClient struct {
	c *client.Client
}

func NewPreferencesClient(c *client.Client) *PreferencesClient {
	return &PreferencesClient{c: c}
}


// UpdateMy PUT /orgs/{orgId}/devices/{deviceId}/me/preferences
func (rc *PreferencesClient) UpdateMy(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/me/preferences")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetMy GET /orgs/{orgId}/devices/{deviceId}/me/preferences
func (rc *PreferencesClient) GetMy(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/me/preferences")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

