// Code generated by rubix-sdk codegen. DO NOT EDIT.
package tag_definitions

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TagDefinitionsClient struct {
	c *client.Client
}

func NewTagDefinitionsClient(c *client.Client) *TagDefinitionsClient {
	return &TagDefinitionsClient{c: c}
}


// List GET /orgs/{orgId}/tag-definitions
func (rc *TagDefinitionsClient) List(orgId string, type_ string, name string, distinct string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	req.SetQueryParam("type", type_)
	req.SetQueryParam("name", name)
	req.SetQueryParam("distinct", distinct)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/tag-definitions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/tag-definitions
func (rc *TagDefinitionsClient) Create(orgId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/tag-definitions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/tag-definitions/{id}
func (rc *TagDefinitionsClient) Delete(orgId string, id string, force bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("force", strconv.FormatBool(force))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Usage GET /orgs/{orgId}/tag-definitions/{id}/usage
func (rc *TagDefinitionsClient) Usage(orgId string, id string, includeNodes bool, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("includeNodes", strconv.FormatBool(includeNodes))
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/{id}/usage")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RenameKey PATCH /orgs/{orgId}/tag-definitions/rename-key
func (rc *TagDefinitionsClient) RenameKey(orgId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/rename-key")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Apply POST /orgs/{orgId}/tag-definitions/{id}/apply
func (rc *TagDefinitionsClient) Apply(orgId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/{id}/apply")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Remove POST /orgs/{orgId}/tag-definitions/{id}/remove
func (rc *TagDefinitionsClient) Remove(orgId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/{id}/remove")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PATCH /orgs/{orgId}/tag-definitions/{id}
func (rc *TagDefinitionsClient) Update(orgId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Search GET /orgs/{orgId}/tag-definitions/search
func (rc *TagDefinitionsClient) Search(orgId string, name string, value string, includeNodes bool, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	req.SetQueryParam("name", name)
	req.SetQueryParam("value", value)
	req.SetQueryParam("includeNodes", strconv.FormatBool(includeNodes))
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/tag-definitions/search")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

