// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nodes_hierarchy

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodesHierarchyClient struct {
	c *client.Client
}

func NewNodesHierarchyClient(c *client.Client) *NodesHierarchyClient {
	return &NodesHierarchyClient{c: c}
}


// GetChildren GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/children
func (rc *NodesHierarchyClient) GetChildren(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/children")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetParent GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/parent
func (rc *NodesHierarchyClient) GetParent(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/parent")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetDescendants GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/descendants
func (rc *NodesHierarchyClient) GetDescendants(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/descendants")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetAncestors GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ancestors
func (rc *NodesHierarchyClient) GetAncestors(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ancestors")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetTree GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/tree
func (rc *NodesHierarchyClient) GetTree(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/tree")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetFamily GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/family
func (rc *NodesHierarchyClient) GetFamily(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/family")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

