// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: admin/v1/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device discovery
type DiscoverRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NetworkInterface string                 `protobuf:"bytes,1,opt,name=network_interface,json=networkInterface,proto3" json:"network_interface,omitempty"` // e.g., "eth0"
	Timeout          int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`                                          // seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverRequest) GetNetworkInterface() string {
	if x != nil {
		return x.NetworkInterface
	}
	return ""
}

func (x *DiscoverRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type DiscoverResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Devices         []*DiscoveredDevice    `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	DiscoveredCount int32                  `protobuf:"varint,2,opt,name=discovered_count,json=discoveredCount,proto3" json:"discovered_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverResponse) GetDevices() []*DiscoveredDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *DiscoverResponse) GetDiscoveredCount() int32 {
	if x != nil {
		return x.DiscoveredCount
	}
	return 0
}

type DiscoveredDevice struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SerialNumber    string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	HardwareModel   string                 `protobuf:"bytes,3,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Role            string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"` // "edge", "gateway", "supervisor"
	Name            string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	OrgId           string                 `protobuf:"bytes,7,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DeviceObjectId  int32                  `protobuf:"varint,8,opt,name=device_object_id,json=deviceObjectId,proto3" json:"device_object_id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,9,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	Firmware        string                 `protobuf:"bytes,10,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                                 // "provisioned", "unprovisioned"
	DiscoveredAt    string                 `protobuf:"bytes,12,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"` // RFC3339 timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoveredDevice) Reset() {
	*x = DiscoveredDevice{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredDevice) ProtoMessage() {}

func (x *DiscoveredDevice) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredDevice.ProtoReflect.Descriptor instead.
func (*DiscoveredDevice) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoveredDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DiscoveredDevice) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *DiscoveredDevice) GetHardwareModel() string {
	if x != nil {
		return x.HardwareModel
	}
	return ""
}

func (x *DiscoveredDevice) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DiscoveredDevice) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DiscoveredDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscoveredDevice) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DiscoveredDevice) GetDeviceObjectId() int32 {
	if x != nil {
		return x.DeviceObjectId
	}
	return 0
}

func (x *DiscoveredDevice) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DiscoveredDevice) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *DiscoveredDevice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiscoveredDevice) GetDiscoveredAt() string {
	if x != nil {
		return x.DiscoveredAt
	}
	return ""
}

// Ping
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`    // IP or device ID
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PingRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reachable     bool                   `protobuf:"varint,1,opt,name=reachable,proto3" json:"reachable,omitempty"`
	RoundTripMs   int32                  `protobuf:"varint,2,opt,name=round_trip_ms,json=roundTripMs,proto3" json:"round_trip_ms,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Empty if reachable=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *PingResponse) GetRoundTripMs() int32 {
	if x != nil {
		return x.RoundTripMs
	}
	return 0
}

func (x *PingResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\x0erubix.admin.v1\"X\n" +
	"\x0fDiscoverRequest\x12+\n" +
	"\x11network_interface\x18\x01 \x01(\tR\x10networkInterface\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"y\n" +
	"\x10DiscoverResponse\x12:\n" +
	"\adevices\x18\x01 \x03(\v2 .rubix.admin.v1.DiscoveredDeviceR\adevices\x12)\n" +
	"\x10discovered_count\x18\x02 \x01(\x05R\x0fdiscoveredCount\"\x87\x03\n" +
	"\x10DiscoveredDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12%\n" +
	"\x0ehardware_model\x18\x03 \x01(\tR\rhardwareModel\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x15\n" +
	"\x06org_id\x18\a \x01(\tR\x05orgId\x12(\n" +
	"\x10device_object_id\x18\b \x01(\x05R\x0edeviceObjectId\x12)\n" +
	"\x10hardware_version\x18\t \x01(\tR\x0fhardwareVersion\x12\x1a\n" +
	"\bfirmware\x18\n" +
	" \x01(\tR\bfirmware\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12#\n" +
	"\rdiscovered_at\x18\f \x01(\tR\fdiscoveredAt\"?\n" +
	"\vPingRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"\xa1\x01\n" +
	"\fPingResponse\x12\x1c\n" +
	"\treachable\x18\x01 \x01(\bR\treachable\x12\"\n" +
	"\rround_trip_ms\x18\x02 \x01(\x05R\vroundTripMs\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB5Z3github.com/NubeIO/rubix-sdk/proto/go/admin/v1;adminb\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_v1_admin_proto_goTypes = []any{
	(*DiscoverRequest)(nil),  // 0: rubix.admin.v1.DiscoverRequest
	(*DiscoverResponse)(nil), // 1: rubix.admin.v1.DiscoverResponse
	(*DiscoveredDevice)(nil), // 2: rubix.admin.v1.DiscoveredDevice
	(*PingRequest)(nil),      // 3: rubix.admin.v1.PingRequest
	(*PingResponse)(nil),     // 4: rubix.admin.v1.PingResponse
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	2, // 0: rubix.admin.v1.DiscoverResponse.devices:type_name -> rubix.admin.v1.DiscoveredDevice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
