// Code generated by rubix-sdk codegen. DO NOT EDIT.
package query

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type QueryClient struct {
	c *client.Client
}

func NewQueryClient(c *client.Client) *QueryClient {
	return &QueryClient{c: c}
}


// Discover POST /orgs/{orgId}/devices/{deviceId}/query/discover
func (rc *QueryClient) Discover(orgId string, deviceId string, depth int, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("depth", strconv.Itoa(depth))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/query/discover")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Filter GET /orgs/{orgId}/devices/{deviceId}/query
func (rc *QueryClient) Filter(orgId string, deviceId string, filter string, runtime bool, limit int, offset int, ports string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("filter", filter)
	req.SetQueryParam("runtime", strconv.FormatBool(runtime))
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	req.SetQueryParam("ports", ports)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/query")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/query
func (rc *QueryClient) Create(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/query")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// History POST /orgs/{orgId}/devices/{deviceId}/query/history
func (rc *QueryClient) History(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/query/history")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Batch POST /orgs/{orgId}/devices/{deviceId}/query/batch
func (rc *QueryClient) Batch(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/query/batch")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

