// Code generated by rubix-sdk codegen. DO NOT EDIT.
package widgets_validate

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type WidgetsValidateClient struct {
	c *client.Client
}

func NewWidgetsValidateClient(c *client.Client) *WidgetsValidateClient {
	return &WidgetsValidateClient{c: c}
}


// Validate GET /orgs/{orgId}/devices/{deviceId}/widgets/{widgetId}/validate
func (rc *WidgetsValidateClient) Validate(orgId string, deviceId string, widgetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/widgets/{widgetId}/validate")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

