// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs_assets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsAssetsClient struct {
	c *client.Client
}

func NewDocsAssetsClient(c *client.Client) *DocsAssetsClient {
	return &DocsAssetsClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets
func (rc *DocsAssetsClient) List(orgId string, deviceId string, collectionId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}
func (rc *DocsAssetsClient) Get(orgId string, deviceId string, collectionId string, assetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"assetId": assetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Download GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}/download
func (rc *DocsAssetsClient) Download(orgId string, deviceId string, collectionId string, assetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"assetId": assetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Upload POST /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets
func (rc *DocsAssetsClient) Upload(orgId string, deviceId string, collectionId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}
func (rc *DocsAssetsClient) Delete(orgId string, deviceId string, collectionId string, assetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"assetId": assetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/assets/{assetId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

