// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: history/v1/history.proto

package history

import (
	v1 "github.com/NubeIO/rubix-sdk/proto/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339 format (e.g., "2026-03-21T10:30:00Z")
	Value         *v1.Value              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryWrite) Reset() {
	*x = HistoryWrite{}
	mi := &file_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryWrite) ProtoMessage() {}

func (x *HistoryWrite) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryWrite.ProtoReflect.Descriptor instead.
func (*HistoryWrite) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryWrite) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HistoryWrite) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HistoryWrite) GetValue() *v1.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type HistoryWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Empty if success=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryWriteResponse) Reset() {
	*x = HistoryWriteResponse{}
	mi := &file_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryWriteResponse) ProtoMessage() {}

func (x *HistoryWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryWriteResponse.ProtoReflect.Descriptor instead.
func (*HistoryWriteResponse) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HistoryWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_history_v1_history_proto protoreflect.FileDescriptor

const file_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"\x18history/v1/history.proto\x12\x10rubix.history.v1\x1a\x16common/v1/common.proto\"s\n" +
	"\fHistoryWrite\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.rubix.common.v1.ValueR\x05value\"F\n" +
	"\x14HistoryWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB9Z7github.com/NubeIO/rubix-sdk/proto/go/history/v1;historyb\x06proto3"

var (
	file_history_v1_history_proto_rawDescOnce sync.Once
	file_history_v1_history_proto_rawDescData []byte
)

func file_history_v1_history_proto_rawDescGZIP() []byte {
	file_history_v1_history_proto_rawDescOnce.Do(func() {
		file_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_v1_history_proto_rawDesc), len(file_history_v1_history_proto_rawDesc)))
	})
	return file_history_v1_history_proto_rawDescData
}

var file_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_history_v1_history_proto_goTypes = []any{
	(*HistoryWrite)(nil),         // 0: rubix.history.v1.HistoryWrite
	(*HistoryWriteResponse)(nil), // 1: rubix.history.v1.HistoryWriteResponse
	(*v1.Value)(nil),             // 2: rubix.common.v1.Value
}
var file_history_v1_history_proto_depIdxs = []int32{
	2, // 0: rubix.history.v1.HistoryWrite.value:type_name -> rubix.common.v1.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_history_v1_history_proto_init() }
func file_history_v1_history_proto_init() {
	if File_history_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_v1_history_proto_rawDesc), len(file_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_history_v1_history_proto_goTypes,
		DependencyIndexes: file_history_v1_history_proto_depIdxs,
		MessageInfos:      file_history_v1_history_proto_msgTypes,
	}.Build()
	File_history_v1_history_proto = out.File
	file_history_v1_history_proto_goTypes = nil
	file_history_v1_history_proto_depIdxs = nil
}
