// Code generated by rubix-sdk codegen. DO NOT EDIT.
package doc_assets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocAssetsClient struct {
	c *client.Client
}

func NewDocAssetsClient(c *client.Client) *DocAssetsClient {
	return &DocAssetsClient{c: c}
}


// Upload POST /orgs/{orgId}/devices/{deviceId}/doc-assets
func (rc *DocAssetsClient) Upload(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/doc-assets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Download GET /orgs/{orgId}/devices/{deviceId}/doc-assets/{nodeId}/download
func (rc *DocAssetsClient) Download(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/doc-assets/{nodeId}/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/doc-assets/{nodeId}
func (rc *DocAssetsClient) Delete(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/doc-assets/{nodeId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

