// Code generated by rubix-sdk codegen. DO NOT EDIT.
package websocket

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type WebsocketClient struct {
	c *client.Client
}

func NewWebsocketClient(c *client.Client) *WebsocketClient {
	return &WebsocketClient{c: c}
}


// ListSessions GET /orgs/{orgId}/devices/{deviceId}/ws/sessions
func (rc *WebsocketClient) ListSessions(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ws/sessions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetSessionDetails GET /orgs/{orgId}/devices/{deviceId}/ws/sessions/{sessionId}
func (rc *WebsocketClient) GetSessionDetails(orgId string, deviceId string, sessionId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ws/sessions/{sessionId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Overrides GET /orgs/{orgId}/devices/{deviceId}/ws/overrides
func (rc *WebsocketClient) Overrides(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ws/overrides")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortValues GET /orgs/{orgId}/devices/{deviceId}/ws/port-values
func (rc *WebsocketClient) PortValues(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ws/port-values")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

