// Code generated by rubix-sdk codegen. DO NOT EDIT.
package association

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type AssociationClient struct {
	c *client.Client
}

func NewAssociationClient(c *client.Client) *AssociationClient {
	return &AssociationClient{c: c}
}


// Delete DELETE /orgs/{orgId}/devices/{deviceId}/associations/{refId}
func (rc *AssociationClient) Delete(orgId string, deviceId string, refId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"refId": refId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/associations/{refId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Search GET /orgs/{orgId}/devices/{deviceId}/nodes/search
func (rc *AssociationClient) Search(orgId string, deviceId string, q string, sourceNodeType string, types string, limit int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("q", q)
	req.SetQueryParam("sourceNodeType", sourceNodeType)
	req.SetQueryParam("types", types)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/search")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/associations
func (rc *AssociationClient) Create(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/associations")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/{nodeId}/associations
func (rc *AssociationClient) List(orgId string, deviceId string, nodeId string, nodeType string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("nodeType", nodeType)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/{nodeId}/associations")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

