// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: node/v1/node.proto

package node

import (
	v1 "github.com/NubeIO/rubix-sdk/proto/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lightweight node snapshot for NATS transport (NOT the database model!)
type NodeSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	Position      *v1.Position           `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSnapshot) Reset() {
	*x = NodeSnapshot{}
	mi := &file_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSnapshot) ProtoMessage() {}

func (x *NodeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSnapshot.ProtoReflect.Descriptor instead.
func (*NodeSnapshot) Descriptor() ([]byte, []int) {
	return file_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeSnapshot) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *NodeSnapshot) GetPosition() *v1.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NodeSnapshot) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *NodeSnapshot) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type QueryNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Haystack query
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNodesRequest) Reset() {
	*x = QueryNodesRequest{}
	mi := &file_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesRequest) ProtoMessage() {}

func (x *QueryNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesRequest.ProtoReflect.Descriptor instead.
func (*QueryNodesRequest) Descriptor() ([]byte, []int) {
	return file_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *QueryNodesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryNodesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryNodesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSnapshot        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNodesResponse) Reset() {
	*x = QueryNodesResponse{}
	mi := &file_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesResponse) ProtoMessage() {}

func (x *QueryNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesResponse.ProtoReflect.Descriptor instead.
func (*QueryNodesResponse) Descriptor() ([]byte, []int) {
	return file_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *QueryNodesResponse) GetNodes() []*NodeSnapshot {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueryNodesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_node_v1_node_proto protoreflect.FileDescriptor

const file_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x12node/v1/node.proto\x12\rrubix.node.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x16common/v1/common.proto\"\xe3\x01\n" +
	"\fNodeSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x123\n" +
	"\bsettings\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bsettings\x125\n" +
	"\bposition\x18\x05 \x01(\v2\x19.rubix.common.v1.PositionR\bposition\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"W\n" +
	"\x11QueryNodesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x12QueryNodesResponse\x121\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1b.rubix.node.v1.NodeSnapshotR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB3Z1github.com/NubeIO/rubix-sdk/proto/go/node/v1;nodeb\x06proto3"

var (
	file_node_v1_node_proto_rawDescOnce sync.Once
	file_node_v1_node_proto_rawDescData []byte
)

func file_node_v1_node_proto_rawDescGZIP() []byte {
	file_node_v1_node_proto_rawDescOnce.Do(func() {
		file_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_v1_node_proto_rawDesc), len(file_node_v1_node_proto_rawDesc)))
	})
	return file_node_v1_node_proto_rawDescData
}

var file_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_v1_node_proto_goTypes = []any{
	(*NodeSnapshot)(nil),       // 0: rubix.node.v1.NodeSnapshot
	(*QueryNodesRequest)(nil),  // 1: rubix.node.v1.QueryNodesRequest
	(*QueryNodesResponse)(nil), // 2: rubix.node.v1.QueryNodesResponse
	(*structpb.Struct)(nil),    // 3: google.protobuf.Struct
	(*v1.Position)(nil),        // 4: rubix.common.v1.Position
}
var file_node_v1_node_proto_depIdxs = []int32{
	3, // 0: rubix.node.v1.NodeSnapshot.settings:type_name -> google.protobuf.Struct
	4, // 1: rubix.node.v1.NodeSnapshot.position:type_name -> rubix.common.v1.Position
	0, // 2: rubix.node.v1.QueryNodesResponse.nodes:type_name -> rubix.node.v1.NodeSnapshot
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_node_v1_node_proto_init() }
func file_node_v1_node_proto_init() {
	if File_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_v1_node_proto_rawDesc), len(file_node_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_v1_node_proto_goTypes,
		DependencyIndexes: file_node_v1_node_proto_depIdxs,
		MessageInfos:      file_node_v1_node_proto_msgTypes,
	}.Build()
	File_node_v1_node_proto = out.File
	file_node_v1_node_proto_goTypes = nil
	file_node_v1_node_proto_depIdxs = nil
}
