// Code generated by rubix-sdk codegen. DO NOT EDIT.
package backup

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type BackupClient struct {
	c *client.Client
}

func NewBackupClient(c *client.Client) *BackupClient {
	return &BackupClient{c: c}
}


// Export POST /orgs/{orgId}/devices/{deviceId}/backup/export
func (rc *BackupClient) Export(orgId string, deviceId string, stream bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("stream", strconv.FormatBool(stream))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/export")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListFiles GET /orgs/{orgId}/devices/{deviceId}/backup/files
func (rc *BackupClient) ListFiles(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteFile DELETE /orgs/{orgId}/devices/{deviceId}/backup/files/{filename}
func (rc *BackupClient) DeleteFile(orgId string, deviceId string, filename string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"filename": filename,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/files/{filename}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ImportStatus GET /orgs/{orgId}/devices/{deviceId}/backup/import/{jobId}/status
func (rc *BackupClient) ImportStatus(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/import/{jobId}/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ValidateContext POST /orgs/{orgId}/devices/{deviceId}/backup/validate-context
func (rc *BackupClient) ValidateContext(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/validate-context")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetBackupChain GET /orgs/{orgId}/devices/{deviceId}/backup/chain
func (rc *BackupClient) GetBackupChain(orgId string, deviceId string, targetTime string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("targetTime", targetTime)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/chain")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DownloadFile GET /orgs/{orgId}/devices/{deviceId}/backup/files/{filename}/download
func (rc *BackupClient) DownloadFile(orgId string, deviceId string, filename string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"filename": filename,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/files/{filename}/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Validate POST /orgs/{orgId}/devices/{deviceId}/backup/validate
func (rc *BackupClient) Validate(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/validate")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/backup/{backupId}
func (rc *BackupClient) Delete(orgId string, deviceId string, backupId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"backupId": backupId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/{backupId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PointInTimeRestore POST /orgs/{orgId}/devices/{deviceId}/backup/point-in-time/restore
func (rc *BackupClient) PointInTimeRestore(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/point-in-time/restore")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Import POST /orgs/{orgId}/devices/{deviceId}/backup/import
func (rc *BackupClient) Import(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/import")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// IncrementalExport POST /orgs/{orgId}/devices/{deviceId}/backup/incremental/export
func (rc *BackupClient) IncrementalExport(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/incremental/export")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ExportStatus GET /orgs/{orgId}/devices/{deviceId}/backup/export/{jobId}/status
func (rc *BackupClient) ExportStatus(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/export/{jobId}/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ExportDownload GET /orgs/{orgId}/devices/{deviceId}/backup/export/{jobId}/download
func (rc *BackupClient) ExportDownload(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/export/{jobId}/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListJobs GET /orgs/{orgId}/devices/{deviceId}/backup/jobs
func (rc *BackupClient) ListJobs(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/jobs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// IncrementalImport POST /orgs/{orgId}/devices/{deviceId}/backup/incremental/import
func (rc *BackupClient) IncrementalImport(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/backup/incremental/import")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

