// Code generated by rubix-sdk codegen. DO NOT EDIT.
package node_profiles

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodeProfilesClient struct {
	c *client.Client
}

func NewNodeProfilesClient(c *client.Client) *NodeProfilesClient {
	return &NodeProfilesClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/node-profiles/{type}
func (rc *NodeProfilesClient) Get(orgId string, deviceId string, type_ string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"type": type_,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-profiles/{type}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetPorts GET /orgs/{orgId}/devices/{deviceId}/node-profiles/{type}/ports
func (rc *NodeProfilesClient) GetPorts(orgId string, deviceId string, type_ string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"type": type_,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-profiles/{type}/ports")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/node-profiles
func (rc *NodeProfilesClient) List(orgId string, deviceId string, nodeType string, pluginId string, identity string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("nodeType", nodeType)
	req.SetQueryParam("pluginId", pluginId)
	req.SetQueryParam("identity", identity)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-profiles")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

