// Code generated by rubix-sdk codegen. DO NOT EDIT.
package orgs

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type OrgsClient struct {
	c *client.Client
}

func NewOrgsClient(c *client.Client) *OrgsClient {
	return &OrgsClient{c: c}
}


// Delete DELETE /orgs/{id}
func (rc *OrgsClient) Delete(id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetLogo GET /orgs/{orgId}/settings/logo
func (rc *OrgsClient) GetLogo(orgId string, variant string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	req.SetQueryParam("variant", variant)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/settings/logo")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetFavicon GET /orgs/{orgId}/settings/favicon
func (rc *OrgsClient) GetFavicon(orgId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/settings/favicon")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{id}
func (rc *OrgsClient) Get(id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetInfo GET /orgs/{id}/info
func (rc *OrgsClient) GetInfo(id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{id}/info")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UploadLogo POST /orgs/{orgId}/settings/logo
func (rc *OrgsClient) UploadLogo(orgId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/settings/logo")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs
func (rc *OrgsClient) List(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs
func (rc *OrgsClient) Create(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{id}
func (rc *OrgsClient) Update(id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

