// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nodes_pages_attach

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodesPagesAttachClient struct {
	c *client.Client
}

func NewNodesPagesAttachClient(c *client.Client) *NodesPagesAttachClient {
	return &NodesPagesAttachClient{c: c}
}


// Attach POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/pages/{pageId}/attach
func (rc *NodesPagesAttachClient) Attach(orgId string, deviceId string, nodeId string, pageId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"pageId": pageId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/pages/{pageId}/attach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Detach DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/pages/{pageId}/detach
func (rc *NodesPagesAttachClient) Detach(orgId string, deviceId string, nodeId string, pageId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"pageId": pageId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/pages/{pageId}/detach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

