// Code generated by rubix-sdk codegen. DO NOT EDIT.
package datastore

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DatastoreClient struct {
	c *client.Client
}

func NewDatastoreClient(c *client.Client) *DatastoreClient {
	return &DatastoreClient{c: c}
}


// Count GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/count
func (rc *DatastoreClient) Count(orgId string, deviceId string, nodeId string, bucket string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/count")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore
func (rc *DatastoreClient) List(orgId string, deviceId string, nodeId string, bucket string, limit int, offset int, orderBy string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	req.SetQueryParam("orderBy", orderBy)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}
func (rc *DatastoreClient) Get(orgId string, deviceId string, nodeId string, index int, bucket string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"index": strconv.Itoa(index),
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}
func (rc *DatastoreClient) Create(orgId string, deviceId string, nodeId string, index int, bucket string, maxVersions int, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"index": strconv.Itoa(index),
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	req.SetQueryParam("maxVersions", strconv.Itoa(maxVersions))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}
func (rc *DatastoreClient) Update(orgId string, deviceId string, nodeId string, index int, bucket string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"index": strconv.Itoa(index),
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}
func (rc *DatastoreClient) Delete(orgId string, deviceId string, nodeId string, index int, bucket string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"index": strconv.Itoa(index),
		
	})
	

	// Set query params
	req.SetQueryParam("bucket", bucket)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/datastore/{index}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

