// Code generated by rubix-sdk codegen. DO NOT EDIT.
package org_admin

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type OrgAdminClient struct {
	c *client.Client
}

func NewOrgAdminClient(c *client.Client) *OrgAdminClient {
	return &OrgAdminClient{c: c}
}


// ListProvisioned GET /orgs/{orgId}/devices/{deviceId}/admin/devices/provisioned
func (rc *OrgAdminClient) ListProvisioned(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/provisioned")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetDeviceConfig GET /orgs/{orgId}/devices/{deviceId}/admin/config
func (rc *OrgAdminClient) GetDeviceConfig(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/config")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetConnectionConfig GET /orgs/{orgId}/devices/{deviceId}/admin/config/connection
func (rc *OrgAdminClient) GetConnectionConfig(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/config/connection")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CreateOrg POST /orgs/{orgId}/devices/{deviceId}/admin/orgs
func (rc *OrgAdminClient) CreateOrg(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/orgs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DiscoverDevices POST /orgs/{orgId}/devices/{deviceId}/admin/devices/discover
func (rc *OrgAdminClient) DiscoverDevices(orgId string, deviceId string, deviceObjectIdRange string, timeout int, add bool, type_ string, rubixNetworkNodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("deviceObjectIdRange", deviceObjectIdRange)
	req.SetQueryParam("timeout", strconv.Itoa(timeout))
	req.SetQueryParam("add", strconv.FormatBool(add))
	req.SetQueryParam("type", type_)
	req.SetQueryParam("rubixNetworkNodeId", rubixNetworkNodeId)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/discover")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ApproveDevice POST /orgs/{orgId}/devices/{deviceId}/admin/devices/{nodeId}/approve
func (rc *OrgAdminClient) ApproveDevice(orgId string, deviceId string, nodeId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/{nodeId}/approve")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListBlacklist GET /orgs/{orgId}/devices/{deviceId}/admin/blacklist
func (rc *OrgAdminClient) ListBlacklist(orgId string, deviceId string, activeOnly bool, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("activeOnly", strconv.FormatBool(activeOnly))
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/blacklist")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListDiscovered GET /orgs/{orgId}/devices/{deviceId}/admin/devices/discovered
func (rc *OrgAdminClient) ListDiscovered(orgId string, deviceId string, status string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("status", status)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/discovered")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateDeviceRole PUT /orgs/{orgId}/devices/{deviceId}/admin/config/role
func (rc *OrgAdminClient) UpdateDeviceRole(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/config/role")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateConnectionConfig PATCH /orgs/{orgId}/devices/{deviceId}/admin/config/connection
func (rc *OrgAdminClient) UpdateConnectionConfig(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/config/connection")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetDeviceInfo GET /orgs/{orgId}/devices/{deviceId}/admin/info
func (rc *OrgAdminClient) GetDeviceInfo(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/info")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListOrgs GET /orgs/{orgId}/devices/{deviceId}/admin/orgs
func (rc *OrgAdminClient) ListOrgs(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/orgs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ProvisionDevice POST /orgs/{orgId}/devices/{deviceId}/admin/devices/provision
func (rc *OrgAdminClient) ProvisionDevice(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/provision")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemoteReadConnectionConfig GET /orgs/{orgId}/devices/{deviceId}/admin/remote/{targetDeviceId}/config/connection
func (rc *OrgAdminClient) RemoteReadConnectionConfig(orgId string, deviceId string, targetDeviceId string, timeout int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"targetDeviceId": targetDeviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("timeout", strconv.Itoa(timeout))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/remote/{targetDeviceId}/config/connection")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemoteUpdateConnectionConfig PATCH /orgs/{orgId}/devices/{deviceId}/admin/remote/{targetDeviceId}/config/connection
func (rc *OrgAdminClient) RemoteUpdateConnectionConfig(orgId string, deviceId string, targetDeviceId string, timeout int, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"targetDeviceId": targetDeviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("timeout", strconv.Itoa(timeout))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/remote/{targetDeviceId}/config/connection")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DenyDevice POST /orgs/{orgId}/devices/{deviceId}/admin/devices/{nodeId}/deny
func (rc *OrgAdminClient) DenyDevice(orgId string, deviceId string, nodeId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/{nodeId}/deny")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BlacklistDevice POST /orgs/{orgId}/devices/{deviceId}/admin/blacklist
func (rc *OrgAdminClient) BlacklistDevice(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/blacklist")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemoveFromBlacklist DELETE /orgs/{orgId}/devices/{deviceId}/admin/blacklist/{blacklistId}
func (rc *OrgAdminClient) RemoveFromBlacklist(orgId string, deviceId string, blacklistId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"blacklistId": blacklistId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/blacklist/{blacklistId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UnprovisionDevice DELETE /orgs/{orgId}/devices/{deviceId}/admin/devices/{serialNumber}/unprovision
func (rc *OrgAdminClient) UnprovisionDevice(orgId string, deviceId string, serialNumber string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"serialNumber": serialNumber,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/admin/devices/{serialNumber}/unprovision")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

