// Code generated by rubix-sdk codegen. DO NOT EDIT.
package email_queue

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type EmailQueueClient struct {
	c *client.Client
}

func NewEmailQueueClient(c *client.Client) *EmailQueueClient {
	return &EmailQueueClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/email-queue/{id}
func (rc *EmailQueueClient) Get(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/email-queue/{id}
func (rc *EmailQueueClient) Delete(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Resend POST /orgs/{orgId}/devices/{deviceId}/email-queue/{id}/resend
func (rc *EmailQueueClient) Resend(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue/{id}/resend")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BulkDelete POST /orgs/{orgId}/devices/{deviceId}/email-queue/bulk/delete
func (rc *EmailQueueClient) BulkDelete(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue/bulk/delete")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Stats GET /orgs/{orgId}/devices/{deviceId}/email-queue/stats
func (rc *EmailQueueClient) Stats(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue/stats")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/email-queue
func (rc *EmailQueueClient) List(orgId string, deviceId string, status string, limit int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("status", status)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/email-queue")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

