// Code generated by rubix-sdk codegen. DO NOT EDIT.
package flows

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type FlowsClient struct {
	c *client.Client
}

func NewFlowsClient(c *client.Client) *FlowsClient {
	return &FlowsClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/flow
func (rc *FlowsClient) Get(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/flow")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PATCH /orgs/{orgId}/devices/{deviceId}/flow
func (rc *FlowsClient) Update(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/flow")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Snapshot GET /orgs/{orgId}/devices/{deviceId}/snapshot
func (rc *FlowsClient) Snapshot(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/snapshot")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/flow
func (rc *FlowsClient) Create(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/flow")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/flow
func (rc *FlowsClient) Delete(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/flow")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

