// Code generated by rubix-sdk codegen. DO NOT EDIT.
package auth

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type AuthClient struct {
	c *client.Client
}

func NewAuthClient(c *client.Client) *AuthClient {
	return &AuthClient{c: c}
}


// SetPin POST /auth/pin/set
func (rc *AuthClient) SetPin(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/pin/set")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemovePin DELETE /auth/pin
func (rc *AuthClient) RemovePin(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/auth/pin")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListServerProfiles GET /auth/server-profiles
func (rc *AuthClient) ListServerProfiles(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/auth/server-profiles")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// TestServerConnection POST /auth/server-profiles/test
func (rc *AuthClient) TestServerConnection(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/server-profiles/test")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Logout POST /auth/logout
func (rc *AuthClient) Logout(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/logout")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CreateServerProfile POST /auth/server-profiles
func (rc *AuthClient) CreateServerProfile(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/server-profiles")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateServerProfile PUT /auth/server-profiles/{id}
func (rc *AuthClient) UpdateServerProfile(id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/auth/server-profiles/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteServerProfile DELETE /auth/server-profiles/{id}
func (rc *AuthClient) DeleteServerProfile(id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/auth/server-profiles/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Signup POST /auth/signup
func (rc *AuthClient) Signup(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/signup")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Login POST /auth/login
func (rc *AuthClient) Login(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/login")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PinLogin POST /auth/pin-login
func (rc *AuthClient) PinLogin(body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/auth/pin-login")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Me GET /auth/me
func (rc *AuthClient) Me(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/auth/me")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

