// Code generated by rubix-sdk codegen. DO NOT EDIT.
package jobs

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type JobsClient struct {
	c *client.Client
}

func NewJobsClient(c *client.Client) *JobsClient {
	return &JobsClient{c: c}
}


// ListAll GET /orgs/{orgId}/devices/{deviceId}/jobs
func (rc *JobsClient) ListAll(orgId string, deviceId string, enabled bool, tags string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("enabled", strconv.FormatBool(enabled))
	req.SetQueryParam("tags", tags)
	req.SetQueryParam("nodeId", nodeId)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/jobs/{jobId}
func (rc *JobsClient) Get(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/{jobId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Stats GET /orgs/{orgId}/devices/{deviceId}/jobs/stats
func (rc *JobsClient) Stats(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/stats")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Enable POST /orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/enable
func (rc *JobsClient) Enable(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/enable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Disable POST /orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/disable
func (rc *JobsClient) Disable(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/disable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RunNow POST /orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/run
func (rc *JobsClient) RunNow(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/{jobId}/run")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Remove DELETE /orgs/{orgId}/devices/{deviceId}/jobs/{jobId}
func (rc *JobsClient) Remove(orgId string, deviceId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/jobs/{jobId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

