// Code generated by rubix-sdk codegen. DO NOT EDIT.
package apikeys

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type ApikeysClient struct {
	c *client.Client
}

func NewApikeysClient(c *client.Client) *ApikeysClient {
	return &ApikeysClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/apikeys
func (rc *ApikeysClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}
func (rc *ApikeysClient) Get(orgId string, deviceId string, apiKeyId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"apiKeyId": apiKeyId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/apikeys
func (rc *ApikeysClient) Create(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}
func (rc *ApikeysClient) Update(orgId string, deviceId string, apiKeyId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"apiKeyId": apiKeyId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}
func (rc *ApikeysClient) Delete(orgId string, deviceId string, apiKeyId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"apiKeyId": apiKeyId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Regenerate POST /orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}/regenerate
func (rc *ApikeysClient) Regenerate(orgId string, deviceId string, apiKeyId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"apiKeyId": apiKeyId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/apikeys/{apiKeyId}/regenerate")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

