// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin/v1/bootstrap.proto

package plugin

import (
	v1 "github.com/NubeIO/rubix-sdk/proto/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap: Node creation from plugins
type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"` // Dynamic JSON settings
	Position      *v1.Position           `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNodeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateNodeRequest) GetPosition() *v1.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CreateNodeRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Empty if success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	FromPort      string                 `protobuf:"bytes,2,opt,name=from_port,json=fromPort,proto3" json:"from_port,omitempty"`
	ToNode        string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	ToPort        string                 `protobuf:"bytes,4,opt,name=to_port,json=toPort,proto3" json:"to_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEdgeRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *CreateEdgeRequest) GetFromPort() string {
	if x != nil {
		return x.FromPort
	}
	return ""
}

func (x *CreateEdgeRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *CreateEdgeRequest) GetToPort() string {
	if x != nil {
		return x.ToPort
	}
	return ""
}

type CreateEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeResponse) Reset() {
	*x = CreateEdgeResponse{}
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeResponse) ProtoMessage() {}

func (x *CreateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEdgeResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *CreateEdgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_v1_bootstrap_proto protoreflect.FileDescriptor

const file_plugin_v1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/v1/bootstrap.proto\x12\x0frubix.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x16common/v1/common.proto\"\xd4\x01\n" +
	"\x11CreateNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x123\n" +
	"\bsettings\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bsettings\x125\n" +
	"\bposition\x18\x05 \x01(\v2\x19.rubix.common.v1.PositionR\bposition\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\"C\n" +
	"\x12CreateNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x7f\n" +
	"\x11CreateEdgeRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x1b\n" +
	"\tfrom_port\x18\x02 \x01(\tR\bfromPort\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\x12\x17\n" +
	"\ato_port\x18\x04 \x01(\tR\x06toPort\"C\n" +
	"\x12CreateEdgeResponse\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB7Z5github.com/NubeIO/rubix-sdk/proto/go/plugin/v1;pluginb\x06proto3"

var (
	file_plugin_v1_bootstrap_proto_rawDescOnce sync.Once
	file_plugin_v1_bootstrap_proto_rawDescData []byte
)

func file_plugin_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_plugin_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_plugin_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_bootstrap_proto_rawDesc), len(file_plugin_v1_bootstrap_proto_rawDesc)))
	})
	return file_plugin_v1_bootstrap_proto_rawDescData
}

var file_plugin_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_v1_bootstrap_proto_goTypes = []any{
	(*CreateNodeRequest)(nil),  // 0: rubix.plugin.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil), // 1: rubix.plugin.v1.CreateNodeResponse
	(*CreateEdgeRequest)(nil),  // 2: rubix.plugin.v1.CreateEdgeRequest
	(*CreateEdgeResponse)(nil), // 3: rubix.plugin.v1.CreateEdgeResponse
	(*structpb.Struct)(nil),    // 4: google.protobuf.Struct
	(*v1.Position)(nil),        // 5: rubix.common.v1.Position
}
var file_plugin_v1_bootstrap_proto_depIdxs = []int32{
	4, // 0: rubix.plugin.v1.CreateNodeRequest.settings:type_name -> google.protobuf.Struct
	5, // 1: rubix.plugin.v1.CreateNodeRequest.position:type_name -> rubix.common.v1.Position
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_bootstrap_proto_init() }
func file_plugin_v1_bootstrap_proto_init() {
	if File_plugin_v1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_bootstrap_proto_rawDesc), len(file_plugin_v1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_plugin_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_plugin_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_plugin_v1_bootstrap_proto = out.File
	file_plugin_v1_bootstrap_proto_goTypes = nil
	file_plugin_v1_bootstrap_proto_depIdxs = nil
}
