// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin/v1/lifecycle.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *NodeSpec              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetSpec() *NodeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type NodeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"` // Dynamic JSON settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeSpec) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type InitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Inputs         []*NodePort            `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs        []*NodePort            `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	SettingsSchema *structpb.Struct       `protobuf:"bytes,3,opt,name=settings_schema,json=settingsSchema,proto3" json:"settings_schema,omitempty"` // JSON Schema for settings
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetInputs() []*NodePort {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *InitResponse) GetOutputs() []*NodePort {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *InitResponse) GetSettingsSchema() *structpb.Struct {
	if x != nil {
		return x.SettingsSchema
	}
	return nil
}

type NodePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`        // "string", "number", "bool", "timestamp"
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`        // "input" or "output"
	Persist       bool                   `protobuf:"varint,5,opt,name=persist,proto3" json:"persist,omitempty"` // Whether to persist port value to database
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePort) Reset() {
	*x = NodePort{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePort) ProtoMessage() {}

func (x *NodePort) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePort.ProtoReflect.Descriptor instead.
func (*NodePort) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *NodePort) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *NodePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodePort) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodePort) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodePort) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GetSchemaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SettingsSchema *structpb.Struct       `protobuf:"bytes,1,opt,name=settings_schema,json=settingsSchema,proto3" json:"settings_schema,omitempty"` // JSON Schema
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *GetSchemaResponse) GetSettingsSchema() *structpb.Struct {
	if x != nil {
		return x.SettingsSchema
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{6}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{7}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{8}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // "running", "not_found", etc.
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Plugin version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_plugin_v1_lifecycle_proto protoreflect.FileDescriptor

const file_plugin_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/v1/lifecycle.proto\x12\x0frubix.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"<\n" +
	"\vInitRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.rubix.plugin.v1.NodeSpecR\x04spec\"c\n" +
	"\bNodeSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x123\n" +
	"\bsettings\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bsettings\"\xb8\x01\n" +
	"\fInitResponse\x121\n" +
	"\x06inputs\x18\x01 \x03(\v2\x19.rubix.plugin.v1.NodePortR\x06inputs\x123\n" +
	"\aoutputs\x18\x02 \x03(\v2\x19.rubix.plugin.v1.NodePortR\aoutputs\x12@\n" +
	"\x0fsettings_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0esettingsSchema\"x\n" +
	"\bNodePort\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x18\n" +
	"\apersist\x18\x05 \x01(\bR\apersist\"/\n" +
	"\x10GetSchemaRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\"U\n" +
	"\x11GetSchemaResponse\x12@\n" +
	"\x0fsettings_schema\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x0esettingsSchema\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"\r\n" +
	"\vPingRequest\"Y\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB7Z5github.com/NubeIO/rubix-sdk/proto/go/plugin/v1;pluginb\x06proto3"

var (
	file_plugin_v1_lifecycle_proto_rawDescOnce sync.Once
	file_plugin_v1_lifecycle_proto_rawDescData []byte
)

func file_plugin_v1_lifecycle_proto_rawDescGZIP() []byte {
	file_plugin_v1_lifecycle_proto_rawDescOnce.Do(func() {
		file_plugin_v1_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_lifecycle_proto_rawDesc), len(file_plugin_v1_lifecycle_proto_rawDesc)))
	})
	return file_plugin_v1_lifecycle_proto_rawDescData
}

var file_plugin_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_v1_lifecycle_proto_goTypes = []any{
	(*InitRequest)(nil),       // 0: rubix.plugin.v1.InitRequest
	(*NodeSpec)(nil),          // 1: rubix.plugin.v1.NodeSpec
	(*InitResponse)(nil),      // 2: rubix.plugin.v1.InitResponse
	(*NodePort)(nil),          // 3: rubix.plugin.v1.NodePort
	(*GetSchemaRequest)(nil),  // 4: rubix.plugin.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil), // 5: rubix.plugin.v1.GetSchemaResponse
	(*CloseRequest)(nil),      // 6: rubix.plugin.v1.CloseRequest
	(*CloseResponse)(nil),     // 7: rubix.plugin.v1.CloseResponse
	(*PingRequest)(nil),       // 8: rubix.plugin.v1.PingRequest
	(*PingResponse)(nil),      // 9: rubix.plugin.v1.PingResponse
	(*structpb.Struct)(nil),   // 10: google.protobuf.Struct
}
var file_plugin_v1_lifecycle_proto_depIdxs = []int32{
	1,  // 0: rubix.plugin.v1.InitRequest.spec:type_name -> rubix.plugin.v1.NodeSpec
	10, // 1: rubix.plugin.v1.NodeSpec.settings:type_name -> google.protobuf.Struct
	3,  // 2: rubix.plugin.v1.InitResponse.inputs:type_name -> rubix.plugin.v1.NodePort
	3,  // 3: rubix.plugin.v1.InitResponse.outputs:type_name -> rubix.plugin.v1.NodePort
	10, // 4: rubix.plugin.v1.InitResponse.settings_schema:type_name -> google.protobuf.Struct
	10, // 5: rubix.plugin.v1.GetSchemaResponse.settings_schema:type_name -> google.protobuf.Struct
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_v1_lifecycle_proto_init() }
func file_plugin_v1_lifecycle_proto_init() {
	if File_plugin_v1_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_lifecycle_proto_rawDesc), len(file_plugin_v1_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_plugin_v1_lifecycle_proto_depIdxs,
		MessageInfos:      file_plugin_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_plugin_v1_lifecycle_proto = out.File
	file_plugin_v1_lifecycle_proto_goTypes = nil
	file_plugin_v1_lifecycle_proto_depIdxs = nil
}
