// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin/v1/process.proto

package plugin

import (
	v1 "github.com/NubeIO/rubix-sdk/proto/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// High-frequency: Process() calls (1000-5000/sec)
type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Inputs        map[string]*v1.Value   `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_plugin_v1_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_process_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProcessRequest) GetInputs() map[string]*v1.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       map[string]*v1.Value   `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Empty if success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_plugin_v1_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_process_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetOutputs() map[string]*v1.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_v1_process_proto protoreflect.FileDescriptor

const file_plugin_v1_process_proto_rawDesc = "" +
	"\n" +
	"\x17plugin/v1/process.proto\x12\x0frubix.plugin.v1\x1a\x16common/v1/common.proto\"\xc1\x01\n" +
	"\x0eProcessRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12C\n" +
	"\x06inputs\x18\x02 \x03(\v2+.rubix.plugin.v1.ProcessRequest.InputsEntryR\x06inputs\x1aQ\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.rubix.common.v1.ValueR\x05value:\x028\x01\"\xc4\x01\n" +
	"\x0fProcessResponse\x12G\n" +
	"\aoutputs\x18\x01 \x03(\v2-.rubix.plugin.v1.ProcessResponse.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1aR\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.rubix.common.v1.ValueR\x05value:\x028\x01B7Z5github.com/NubeIO/rubix-sdk/proto/go/plugin/v1;pluginb\x06proto3"

var (
	file_plugin_v1_process_proto_rawDescOnce sync.Once
	file_plugin_v1_process_proto_rawDescData []byte
)

func file_plugin_v1_process_proto_rawDescGZIP() []byte {
	file_plugin_v1_process_proto_rawDescOnce.Do(func() {
		file_plugin_v1_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_process_proto_rawDesc), len(file_plugin_v1_process_proto_rawDesc)))
	})
	return file_plugin_v1_process_proto_rawDescData
}

var file_plugin_v1_process_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_v1_process_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: rubix.plugin.v1.ProcessRequest
	(*ProcessResponse)(nil), // 1: rubix.plugin.v1.ProcessResponse
	nil,                     // 2: rubix.plugin.v1.ProcessRequest.InputsEntry
	nil,                     // 3: rubix.plugin.v1.ProcessResponse.OutputsEntry
	(*v1.Value)(nil),        // 4: rubix.common.v1.Value
}
var file_plugin_v1_process_proto_depIdxs = []int32{
	2, // 0: rubix.plugin.v1.ProcessRequest.inputs:type_name -> rubix.plugin.v1.ProcessRequest.InputsEntry
	3, // 1: rubix.plugin.v1.ProcessResponse.outputs:type_name -> rubix.plugin.v1.ProcessResponse.OutputsEntry
	4, // 2: rubix.plugin.v1.ProcessRequest.InputsEntry.value:type_name -> rubix.common.v1.Value
	4, // 3: rubix.plugin.v1.ProcessResponse.OutputsEntry.value:type_name -> rubix.common.v1.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_v1_process_proto_init() }
func file_plugin_v1_process_proto_init() {
	if File_plugin_v1_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_process_proto_rawDesc), len(file_plugin_v1_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_process_proto_goTypes,
		DependencyIndexes: file_plugin_v1_process_proto_depIdxs,
		MessageInfos:      file_plugin_v1_process_proto_msgTypes,
	}.Build()
	File_plugin_v1_process_proto = out.File
	file_plugin_v1_process_proto_goTypes = nil
	file_plugin_v1_process_proto_depIdxs = nil
}
