// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin/v1/rpc.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPCRequest wraps all plugin RPC calls
type RPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                        // "init", "process", "close", "ping", etc.
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // Target node instance ID
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // Serialized method-specific request (ProcessRequest, InitRequest, etc.)
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // For tracing (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequest) Reset() {
	*x = RPCRequest{}
	mi := &file_plugin_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequest) ProtoMessage() {}

func (x *RPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequest.ProtoReflect.Descriptor instead.
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RPCRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// RPCResponse wraps all plugin RPC responses
type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // Error message if success=false
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                            // Serialized method-specific response (ProcessResponse, InitResponse, etc.)
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Echo request_id for tracing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_plugin_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RPCResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RPCResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_plugin_v1_rpc_proto protoreflect.FileDescriptor

const file_plugin_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/v1/rpc.proto\x12\x0frubix.plugin.v1\"v\n" +
	"\n" +
	"RPCRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"p\n" +
	"\vRPCResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestIdB7Z5github.com/NubeIO/rubix-sdk/proto/go/plugin/v1;pluginb\x06proto3"

var (
	file_plugin_v1_rpc_proto_rawDescOnce sync.Once
	file_plugin_v1_rpc_proto_rawDescData []byte
)

func file_plugin_v1_rpc_proto_rawDescGZIP() []byte {
	file_plugin_v1_rpc_proto_rawDescOnce.Do(func() {
		file_plugin_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_rpc_proto_rawDesc), len(file_plugin_v1_rpc_proto_rawDesc)))
	})
	return file_plugin_v1_rpc_proto_rawDescData
}

var file_plugin_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_v1_rpc_proto_goTypes = []any{
	(*RPCRequest)(nil),  // 0: rubix.plugin.v1.RPCRequest
	(*RPCResponse)(nil), // 1: rubix.plugin.v1.RPCResponse
}
var file_plugin_v1_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_v1_rpc_proto_init() }
func file_plugin_v1_rpc_proto_init() {
	if File_plugin_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_rpc_proto_rawDesc), len(file_plugin_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_rpc_proto_goTypes,
		DependencyIndexes: file_plugin_v1_rpc_proto_depIdxs,
		MessageInfos:      file_plugin_v1_rpc_proto_msgTypes,
	}.Build()
	File_plugin_v1_rpc_proto = out.File
	file_plugin_v1_rpc_proto_goTypes = nil
	file_plugin_v1_rpc_proto_depIdxs = nil
}
