// Code generated by rubix-sdk codegen. DO NOT EDIT.
package insights

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type InsightsClient struct {
	c *client.Client
}

func NewInsightsClient(c *client.Client) *InsightsClient {
	return &InsightsClient{c: c}
}


// Assign POST /orgs/{orgId}/devices/{deviceId}/insights/{id}/assign
func (rc *InsightsClient) Assign(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/assign")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Resolve POST /orgs/{orgId}/devices/{deviceId}/insights/{id}/resolve
func (rc *InsightsClient) Resolve(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/resolve")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// AiRequest POST /orgs/{orgId}/devices/{deviceId}/insights/{id}/ai-request
func (rc *InsightsClient) AiRequest(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/ai-request")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// AiHistory GET /orgs/{orgId}/devices/{deviceId}/insights/{id}/ai-history
func (rc *InsightsClient) AiHistory(orgId string, deviceId string, id string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/ai-history")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Stats GET /orgs/{orgId}/devices/{deviceId}/insights/stats
func (rc *InsightsClient) Stats(orgId string, deviceId string, category string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("category", category)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/stats")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateStatus POST /orgs/{orgId}/devices/{deviceId}/insights/{id}/status
func (rc *InsightsClient) UpdateStatus(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Events GET /orgs/{orgId}/devices/{deviceId}/insights/{id}/events
func (rc *InsightsClient) Events(orgId string, deviceId string, id string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}/events")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/insights
func (rc *InsightsClient) List(orgId string, deviceId string, status string, priority string, impactLevel string, assignedTo string, building string, category string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("status", status)
	req.SetQueryParam("priority", priority)
	req.SetQueryParam("impactLevel", impactLevel)
	req.SetQueryParam("assignedTo", assignedTo)
	req.SetQueryParam("building", building)
	req.SetQueryParam("category", category)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/insights/{id}
func (rc *InsightsClient) Get(orgId string, deviceId string, id string, includeDetail bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("includeDetail", strconv.FormatBool(includeDetail))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/insights
func (rc *InsightsClient) Create(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/insights")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

