// Code generated by rubix-sdk codegen. DO NOT EDIT.
package logs

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type LogsClient struct {
	c *client.Client
}

func NewLogsClient(c *client.Client) *LogsClient {
	return &LogsClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/logs
func (rc *LogsClient) Get(orgId string, deviceId string, tail int, level string, component string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("tail", strconv.Itoa(tail))
	req.SetQueryParam("level", level)
	req.SetQueryParam("component", component)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/logs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Clear DELETE /orgs/{orgId}/devices/{deviceId}/logs
func (rc *LogsClient) Clear(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/logs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

