// Code generated by rubix-sdk codegen. DO NOT EDIT.
package schemas

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type SchemasClient struct {
	c *client.Client
}

func NewSchemasClient(c *client.Client) *SchemasClient {
	return &SchemasClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/node-types/schemas
func (rc *SchemasClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-types/schemas")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/schema
func (rc *SchemasClient) Get(orgId string, deviceId string, nodeType string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeType": nodeType,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/schema")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListByType GET /orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/settings-schemas/list
func (rc *SchemasClient) ListByType(orgId string, deviceId string, nodeType string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeType": nodeType,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/settings-schemas/list")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetByType GET /orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/settings-schemas/{schemaName}
func (rc *SchemasClient) GetByType(orgId string, deviceId string, nodeType string, schemaName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeType": nodeType,
		"schemaName": schemaName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/node-types/{nodeType}/settings-schemas/{schemaName}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

