// Code generated by rubix-sdk codegen. DO NOT EDIT.
package access

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type AccessClient struct {
	c *client.Client
}

func NewAccessClient(c *client.Client) *AccessClient {
	return &AccessClient{c: c}
}


// Test POST /orgs/{orgId}/devices/{deviceId}/access/test
func (rc *AccessClient) Test(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/access/test")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// TestPages POST /orgs/{orgId}/devices/{deviceId}/access/pages/test
func (rc *AccessClient) TestPages(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/access/pages/test")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

