// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nav

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NavClient struct {
	c *client.Client
}

func NewNavClient(c *client.Client) *NavClient {
	return &NavClient{c: c}
}


// OrgSidebar GET /orgs/{orgId}/sidebar
func (rc *NavClient) OrgSidebar(orgId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/sidebar")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// NavInfo GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/nav-info
func (rc *NavClient) NavInfo(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/nav-info")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// NavSearch GET /orgs/{orgId}/devices/{deviceId}/nav/search
func (rc *NavClient) NavSearch(orgId string, deviceId string, q string, limit int, type_ string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("q", q)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("type", type_)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/search")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListTeams GET /orgs/{orgId}/devices/{deviceId}/nav/{navId}/teams
func (rc *NavClient) ListTeams(orgId string, deviceId string, navId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"navId": navId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/{navId}/teams")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/nav
func (rc *NavClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/nav/{id}
func (rc *NavClient) Update(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/nav/{id}
func (rc *NavClient) Delete(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Sidebar GET /orgs/{orgId}/devices/{deviceId}/sidebar
func (rc *NavClient) Sidebar(orgId string, deviceId string, depth int, includeRemoteDevices bool, nodeType string, nodeId string, withBreadcrumbs bool, pageView string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("depth", strconv.Itoa(depth))
	req.SetQueryParam("includeRemoteDevices", strconv.FormatBool(includeRemoteDevices))
	req.SetQueryParam("nodeType", nodeType)
	req.SetQueryParam("nodeId", nodeId)
	req.SetQueryParam("withBreadcrumbs", strconv.FormatBool(withBreadcrumbs))
	req.SetQueryParam("pageView", pageView)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/sidebar")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetOrgs GET /sidebar
func (rc *NavClient) GetOrgs(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/sidebar")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListUsers GET /orgs/{orgId}/devices/{deviceId}/nav/{navId}/users
func (rc *NavClient) ListUsers(orgId string, deviceId string, navId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"navId": navId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/{navId}/users")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/nav/{id}
func (rc *NavClient) Get(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/nav
func (rc *NavClient) Create(orgId string, deviceId string, allowUnknown bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("allowUnknown", strconv.FormatBool(allowUnknown))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nav")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// NavChildren GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/nav-children
func (rc *NavClient) NavChildren(orgId string, deviceId string, nodeId string, nodeType string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("nodeType", nodeType)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/nav-children")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

