// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs_access

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsAccessClient struct {
	c *client.Client
}

func NewDocsAccessClient(c *client.Client) *DocsAccessClient {
	return &DocsAccessClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/access
func (rc *DocsAccessClient) Get(orgId string, deviceId string, collectionId string, docId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/access")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/access
func (rc *DocsAccessClient) Update(orgId string, deviceId string, collectionId string, docId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/access")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

