// Code generated by rubix-sdk codegen. DO NOT EDIT.
package diagnostics

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DiagnosticsClient struct {
	c *client.Client
}

func NewDiagnosticsClient(c *client.Client) *DiagnosticsClient {
	return &DiagnosticsClient{c: c}
}


// Health GET /orgs/{orgId}/devices/{deviceId}/diagnostics/health
func (rc *DiagnosticsClient) Health(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/diagnostics/health")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// NodeStatus GET /orgs/{orgId}/devices/{deviceId}/diagnostics/node-status/{nodeId}
func (rc *DiagnosticsClient) NodeStatus(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/diagnostics/node-status/{nodeId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

