// Code generated by rubix-sdk codegen. DO NOT EDIT.
package rxai

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type RxaiClient struct {
	c *client.Client
}

func NewRxaiClient(c *client.Client) *RxaiClient {
	return &RxaiClient{c: c}
}


// ListSessions GET /orgs/{orgId}/devices/{deviceId}/rxai/sessions
func (rc *RxaiClient) ListSessions(orgId string, deviceId string, status string, userId string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("status", status)
	req.SetQueryParam("userId", userId)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetSession GET /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}
func (rc *RxaiClient) GetSession(orgId string, deviceId string, sessionId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SendMessage POST /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/messages
func (rc *RxaiClient) SendMessage(orgId string, deviceId string, sessionId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/messages")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// StopSession POST /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/stop
func (rc *RxaiClient) StopSession(orgId string, deviceId string, sessionId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/stop")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteSession DELETE /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}
func (rc *RxaiClient) DeleteSession(orgId string, deviceId string, sessionId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListInteractions GET /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/interactions
func (rc *RxaiClient) ListInteractions(orgId string, deviceId string, sessionId string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/interactions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListActions GET /orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/actions
func (rc *RxaiClient) ListActions(orgId string, deviceId string, sessionId string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"sessionId": sessionId,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions/{sessionId}/actions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CreateSession POST /orgs/{orgId}/devices/{deviceId}/rxai/sessions
func (rc *RxaiClient) CreateSession(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/rxai/sessions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

