// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsClient struct {
	c *client.Client
}

func NewDocsClient(c *client.Client) *DocsClient {
	return &DocsClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}
func (rc *DocsClient) Get(orgId string, deviceId string, collectionId string, docId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs
func (rc *DocsClient) Create(orgId string, deviceId string, collectionId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}
func (rc *DocsClient) Update(orgId string, deviceId string, collectionId string, docId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}
func (rc *DocsClient) Delete(orgId string, deviceId string, collectionId string, docId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs
func (rc *DocsClient) List(orgId string, deviceId string, collectionId string, visibility string, tags string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		
	})
	

	// Set query params
	req.SetQueryParam("visibility", visibility)
	req.SetQueryParam("tags", tags)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

