// Code generated by rubix-sdk codegen. DO NOT EDIT.
package plugins

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PluginsClient struct {
	c *client.Client
}

func NewPluginsClient(c *client.Client) *PluginsClient {
	return &PluginsClient{c: c}
}


// Start POST /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/start
func (rc *PluginsClient) Start(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/start")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Stop POST /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/stop
func (rc *PluginsClient) Stop(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/stop")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Backup POST /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/backup
func (rc *PluginsClient) Backup(orgId string, deviceId string, pluginId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/backup")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Logs GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/logs
func (rc *PluginsClient) Logs(orgId string, deviceId string, pluginId string, tail int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	req.SetQueryParam("tail", strconv.Itoa(tail))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/logs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Config GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/config
func (rc *PluginsClient) Config(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/config")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Frontend GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/frontend
func (rc *PluginsClient) Frontend(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/frontend")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetWidgets GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/widgets
func (rc *PluginsClient) GetWidgets(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/widgets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CallWidget POST /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/widgets/{widgetId}/call
func (rc *PluginsClient) CallWidget(orgId string, deviceId string, pluginId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/widgets/{widgetId}/call")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/plugins
func (rc *PluginsClient) List(orgId string, deviceId string, extended bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("extended", strconv.FormatBool(extended))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}
func (rc *PluginsClient) Get(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Restore POST /orgs/{orgId}/devices/{deviceId}/plugins/restore
func (rc *PluginsClient) Restore(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/restore")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}
func (rc *PluginsClient) Delete(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Ping GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/ping
func (rc *PluginsClient) Ping(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/ping")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Migrations GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/migrations
func (rc *PluginsClient) Migrations(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/migrations")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetAllWidgets GET /orgs/{orgId}/plugins/widgets/all
func (rc *PluginsClient) GetAllWidgets(orgId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/plugins/widgets/all")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Install POST /orgs/{orgId}/devices/{deviceId}/plugins/install
func (rc *PluginsClient) Install(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/install")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Status GET /orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/status
func (rc *PluginsClient) Status(orgId string, deviceId string, pluginId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugins/{pluginId}/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

