// Code generated by rubix-sdk codegen. DO NOT EDIT.
package hierarchy

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type HierarchyClient struct {
	c *client.Client
}

func NewHierarchyClient(c *client.Client) *HierarchyClient {
	return &HierarchyClient{c: c}
}


// ListGrouped GET /orgs/{orgId}/devices/{deviceId}/hierarchy/grouped
func (rc *HierarchyClient) ListGrouped(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/hierarchy/grouped")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetStats GET /orgs/{orgId}/devices/{deviceId}/hierarchy/stats
func (rc *HierarchyClient) GetStats(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/hierarchy/stats")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetFullTree GET /orgs/{orgId}/devices/{deviceId}/hierarchy/tree
func (rc *HierarchyClient) GetFullTree(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/hierarchy/tree")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListOrphans GET /orgs/{orgId}/devices/{deviceId}/hierarchy/orphans
func (rc *HierarchyClient) ListOrphans(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/hierarchy/orphans")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

