package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"github.com/NubeIO/rubix-sdk/internal/codegen"
)

// go run ./cmd/codegen/client --ras-path=../rubix/configs/ras

var goReservedKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

func sanitizePackageName(name string) string {
	sanitized := strings.ReplaceAll(name, "-", "_")
	sanitized = strings.ReplaceAll(sanitized, ".", "_")
	return strings.ToLower(sanitized)
}

func sanitizeIdentifier(name string) string {
	sanitized := strings.ReplaceAll(name, "-", "_")
	sanitized = strings.ReplaceAll(sanitized, ".", "_")
	sanitized = strings.ReplaceAll(sanitized, "[", "_")
	sanitized = strings.ReplaceAll(sanitized, "]", "")
	return sanitized
}

func sanitizeParamName(name string) string {
	sanitized := sanitizeIdentifier(name)
	if goReservedKeywords[sanitized] {
		return sanitized + "_"
	}
	return sanitized
}

func toExportedName(name string) string {
	sanitized := sanitizeIdentifier(name)

	parts := strings.Split(sanitized, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	result := strings.Join(parts, "")

	if len(result) > 0 {
		runes := []rune(result)
		runes[0] = unicode.ToUpper(runes[0])
		result = string(runes)
	}

	return result
}

func main() {
	rasPath := flag.String("ras-path", "", "Path to RAS config directory (e.g., ../rubix/configs/ras)")
	outputDir := flag.String("output", "pkg/client", "Output directory for generated client")
	flag.Parse()

	if *rasPath == "" {
		fmt.Fprintln(os.Stderr, "Error: --ras-path is required")
		fmt.Fprintln(os.Stderr, "Usage: go run ./cmd/codegen/client --ras-path=../rubix/configs/ras")
		os.Exit(1)
	}

	ras, err := codegen.LoadRAS(*rasPath)
	if err != nil {
		panic(err)
	}

	clientDir := *outputDir
	if err := os.MkdirAll(clientDir, 0755); err != nil {
		panic(err)
	}

	generateBaseClient(clientDir, ras.Prefix.Rest)

	for resourceName, resource := range ras.Resources {
		generateResourceClient(clientDir, resourceName, resource, ras.Prefix.Rest)
	}

	fmt.Printf("Client code generation complete → %s\n", clientDir)
}

func generateBaseClient(dir, prefix string) {
	tmpl := `// Code generated by rubix-sdk codegen. DO NOT EDIT.
package client

import (
	"github.com/go-resty/resty/v2"
)

type Client struct {
	R      *resty.Client
	Prefix string
}

func NewClient(baseURL string) *Client {
	r := resty.New().SetBaseURL(baseURL)
	return &Client{
		R:      r,
		Prefix: "{{.Prefix}}",
	}
}

type Option func(*resty.Request)

// WithQueryParam adds a query parameter
func WithQueryParam(key, value string) Option {
	return func(r *resty.Request) {
		r.SetQueryParam(key, value)
	}
}

// WithHeader adds a header
func WithHeader(key, value string) Option {
	return func(r *resty.Request) {
		r.SetHeader(key, value)
	}
}

// WithToken sets a bearer auth token
func WithToken(token string) Option {
	return func(r *resty.Request) {
		r.SetAuthToken(token)
	}
}
`

	data := struct {
		Prefix string
	}{
		Prefix: prefix,
	}

	file := filepath.Join(dir, "client.go")
	writeTemplate(file, tmpl, data)
}

func generateResourceClient(dir, resourceName string, resource codegen.Resource, prefix string) {
	pkgName := sanitizePackageName(resourceName)
	exportedName := toExportedName(resourceName)

	resourceDir := filepath.Join(dir, pkgName)
	if err := os.MkdirAll(resourceDir, 0755); err != nil {
		panic(err)
	}

	tmpl := `// Code generated by rubix-sdk codegen. DO NOT EDIT.
package {{.PackageName}}

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type {{.ExportedName}}Client struct {
	c *client.Client
}

func New{{.ExportedName}}Client(c *client.Client) *{{.ExportedName}}Client {
	return &{{.ExportedName}}Client{c: c}
}

{{range .Actions}}
// {{.ExportedName}} {{.Method}} {{.Path}}
func (rc *{{$.ExportedName}}Client) {{.ExportedName}}({{.Params}}) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	{{if .PathParams}}req.SetPathParams(map[string]string{
		{{range .PathParams}}"{{.OriginalName}}": {{convertPath .SanitizedName .Type}},
		{{end}}
	})
	{{end}}

	// Set query params
	{{range .QueryParams}}req.SetQueryParam("{{.OriginalName}}", {{convert .SanitizedName .Type}})
	{{end}}

	// Set body if present
	{{if .HasBody}}req.SetBody(body)
	{{end}}

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.{{.RestyMethod}}(rc.c.Prefix + "{{.Path}}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}
{{end}}
`

	actions := []ActionData{}
	hasInteger := false
	hasNumber := false
	seenExportedNames := make(map[string]int)

	for actionName, action := range resource.Actions {
		pathParams := []ParamData{}
		queryParams := []ParamData{}
		hasBody := false

		params := []string{}
		for _, arg := range action.Args {
			sanitizedName := sanitizeParamName(arg.Name)

			if arg.In == "path" {
				pathParams = append(pathParams, ParamData{
					OriginalName:  arg.Name,
					SanitizedName: sanitizedName,
					Type:          arg.Type,
				})
				params = append(params, fmt.Sprintf("%s %s", sanitizedName, goType(arg.Type)))
			} else if arg.In == "query" {
				queryParams = append(queryParams, ParamData{
					OriginalName:  arg.Name,
					SanitizedName: sanitizedName,
					Type:          arg.Type,
				})
				params = append(params, fmt.Sprintf("%s %s", sanitizedName, goType(arg.Type)))
				if arg.Type == "integer" {
					hasInteger = true
				} else if arg.Type == "number" {
					hasNumber = true
				}
			}
		}
		if action.Body.SchemaRef != "" || action.Body.Type != "" {
			hasBody = true
			params = append(params, "body interface{}")
		}

		paramStr := strings.Join(params, ", ")
		if len(params) > 0 {
			paramStr += ", "
		}
		paramStr += "opts ...client.Option"

		exportedActionName := toExportedName(actionName)
		if count, exists := seenExportedNames[exportedActionName]; exists {
			seenExportedNames[exportedActionName] = count + 1
			exportedActionName = fmt.Sprintf("%s%d", exportedActionName, count+1)
		} else {
			seenExportedNames[exportedActionName] = 1
		}

		actions = append(actions, ActionData{
			Name:         actionName,
			ExportedName: exportedActionName,
			Method:       action.Rest.Method,
			Path:         action.Rest.Path,
			Params:       paramStr,
			PathParams:   pathParams,
			QueryParams:  queryParams,
			HasBody:      hasBody,
			RestyMethod:  restyMethod(action.Rest.Method),
		})
	}

	data := struct {
		PackageName  string
		ExportedName string
		Actions      []ActionData
		HasInteger   bool
		HasNumber    bool
	}{
		PackageName:  pkgName,
		ExportedName: exportedName,
		Actions:      actions,
		HasInteger:   hasInteger,
		HasNumber:    hasNumber,
	}

	file := filepath.Join(resourceDir, pkgName+".go")
	writeTemplate(file, tmpl, data)
}

type ActionData struct {
	Name         string
	ExportedName string
	Method       string
	Path         string
	Params       string
	PathParams   []ParamData
	QueryParams  []ParamData
	HasBody      bool
	RestyMethod  string
}

type ParamData struct {
	OriginalName  string
	SanitizedName string
	Type          string
}

func goType(t string) string {
	switch t {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "number":
		return "float64"
	default:
		return "string"
	}
}

func restyMethod(method string) string {
	switch strings.ToUpper(method) {
	case "GET":
		return "Get"
	case "POST":
		return "Post"
	case "PUT":
		return "Put"
	case "DELETE":
		return "Delete"
	case "PATCH":
		return "Patch"
	default:
		return "Get"
	}
}

func writeTemplate(file, tmpl string, data interface{}) {
	t, err := template.New("").Funcs(template.FuncMap{
		"convertPath": func(name, typ string) string {
			switch typ {
			case "integer":
				return "strconv.Itoa(" + name + ")"
			case "boolean":
				return "strconv.FormatBool(" + name + ")"
			case "number":
				return "fmt.Sprintf(\"%g\", " + name + ")"
			default:
				return name
			}
		},
		"convert": func(name, typ string) string {
			switch typ {
			case "integer":
				return "strconv.Itoa(" + name + ")"
			case "boolean":
				return "strconv.FormatBool(" + name + ")"
			case "number":
				return "fmt.Sprintf(\"%f\", " + name + ")"
			default:
				return name
			}
		},
	}).Parse(tmpl)
	if err != nil {
		panic(err)
	}

	f, err := os.Create(file)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	if err := t.Execute(f, data); err != nil {
		panic(err)
	}
}
