// Code generated by rubix-sdk codegen. DO NOT EDIT.
package refs

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type RefsClient struct {
	c *client.Client
}

func NewRefsClient(c *client.Client) *RefsClient {
	return &RefsClient{c: c}
}


// Create POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs
func (rc *RefsClient) Create(orgId string, deviceId string, nodeId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs
func (rc *RefsClient) List(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs/{refName}
func (rc *RefsClient) Get(orgId string, deviceId string, nodeId string, refName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"refName": refName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs/{refName}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs/{refName}
func (rc *RefsClient) Delete(orgId string, deviceId string, nodeId string, refName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"refName": refName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs/{refName}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListByRef GET /orgs/{orgId}/devices/{deviceId}/refs/{refName}/{targetId}/nodes
func (rc *RefsClient) ListByRef(orgId string, deviceId string, refName string, targetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"refName": refName,
		"targetId": targetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/refs/{refName}/{targetId}/nodes")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListToNode GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs-to
func (rc *RefsClient) ListToNode(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/refs-to")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BatchReorder PATCH /orgs/{orgId}/devices/{deviceId}/refs/batch-reorder
func (rc *RefsClient) BatchReorder(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/refs/batch-reorder")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

