// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nodes

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodesClient struct {
	c *client.Client
}

func NewNodesClient(c *client.Client) *NodesClient {
	return &NodesClient{c: c}
}


// PortValuesList GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values
func (rc *NodesClient) PortValuesList(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortValueSet POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}
func (rc *NodesClient) PortValueSet(orgId string, deviceId string, nodeId string, portId string, setOutput bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	req.SetQueryParam("setOutput", strconv.FormatBool(setOutput))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandsGet GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{name}
func (rc *NodesClient) CommandsGet(orgId string, deviceId string, nodeId string, name string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"name": name,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{name}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BulkCreate POST /orgs/{orgId}/devices/{deviceId}/nodes/bulk
func (rc *NodesClient) BulkCreate(orgId string, deviceId string, allowUnknown bool, delete bool, start bool, parentId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("allowUnknown", strconv.FormatBool(allowUnknown))
	req.SetQueryParam("delete", strconv.FormatBool(delete))
	req.SetQueryParam("start", strconv.FormatBool(start))
	req.SetQueryParam("parentId", parentId)
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/bulk")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BulkUpdate PUT /orgs/{orgId}/devices/{deviceId}/nodes/bulk
func (rc *NodesClient) BulkUpdate(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/bulk")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Docs GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}/docs
func (rc *NodesClient) Docs(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/docs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SettingsWithSchema GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema
func (rc *NodesClient) SettingsWithSchema(orgId string, deviceId string, id string, withoutSchema bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("withoutSchema", strconv.FormatBool(withoutSchema))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SettingsPatch PATCH /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings
func (rc *NodesClient) SettingsPatch(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BulkDelete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/bulk
func (rc *NodesClient) BulkDelete(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/bulk")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandsList GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands
func (rc *NodesClient) CommandsList(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateId PATCH /orgs/{orgId}/devices/{deviceId}/nodes/{id}/update-id
func (rc *NodesClient) UpdateId(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/update-id")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SettingsSchemasList GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema/list
func (rc *NodesClient) SettingsSchemasList(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema/list")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Trigger POST /orgs/{orgId}/devices/{deviceId}/nodes/{id}/trigger
func (rc *NodesClient) Trigger(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/trigger")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandDelete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute
func (rc *NodesClient) CommandDelete(orgId string, deviceId string, nodeId string, commandName string, async bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"commandName": commandName,
		
	})
	

	// Set query params
	req.SetQueryParam("async", strconv.FormatBool(async))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// JobsDelete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs/{jobId}
func (rc *NodesClient) JobsDelete(orgId string, deviceId string, nodeId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs/{jobId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Deploy POST /orgs/{orgId}/devices/{deviceId}/nodes/{id}/deploy
func (rc *NodesClient) Deploy(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/deploy")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/nodes/{id}
func (rc *NodesClient) Update(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteAll DELETE /orgs/{orgId}/devices/{deviceId}/nodes
func (rc *NodesClient) DeleteAll(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// TestRun POST /orgs/{orgId}/devices/{deviceId}/nodes/{id}/test-run
func (rc *NodesClient) TestRun(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/test-run")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Settings GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings
func (rc *NodesClient) Settings(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortValueGet GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}
func (rc *NodesClient) PortValueGet(orgId string, deviceId string, nodeId string, portId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandRunBulk POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/command-runs/bulk
func (rc *NodesClient) CommandRunBulk(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/command-runs/bulk")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// JobsList GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs
func (rc *NodesClient) JobsList(orgId string, deviceId string, nodeId string, status string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("status", status)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{id}
func (rc *NodesClient) Delete(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandRun POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/command-runs
func (rc *NodesClient) CommandRun(orgId string, deviceId string, nodeId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/command-runs")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Actions POST /orgs/{orgId}/devices/{deviceId}/nodes/actions
func (rc *NodesClient) Actions(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/actions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandPost POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute
func (rc *NodesClient) CommandPost(orgId string, deviceId string, nodeId string, commandName string, async bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"commandName": commandName,
		
	})
	

	// Set query params
	req.SetQueryParam("async", strconv.FormatBool(async))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandPatch PATCH /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute
func (rc *NodesClient) CommandPatch(orgId string, deviceId string, nodeId string, commandName string, async bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"commandName": commandName,
		
	})
	

	// Set query params
	req.SetQueryParam("async", strconv.FormatBool(async))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}
func (rc *NodesClient) Get(orgId string, deviceId string, id string, includeValues bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	req.SetQueryParam("includeValues", strconv.FormatBool(includeValues))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// MetadataUpdate PATCH /orgs/{orgId}/devices/{deviceId}/nodes/{id}/metadata
func (rc *NodesClient) MetadataUpdate(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/metadata")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortsList GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports
func (rc *NodesClient) PortsList(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortGet GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports/{portId}
func (rc *NodesClient) PortGet(orgId string, deviceId string, nodeId string, portId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PortValueClear DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}
func (rc *NodesClient) PortValueClear(orgId string, deviceId string, nodeId string, portId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portId": portId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/port-values/{portId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BatchUpdate POST /orgs/{orgId}/devices/{deviceId}/nodes/batch-update
func (rc *NodesClient) BatchUpdate(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/batch-update")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/nodes
func (rc *NodesClient) Create(orgId string, deviceId string, allowUnknown bool, parentId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("allowUnknown", strconv.FormatBool(allowUnknown))
	req.SetQueryParam("parentId", parentId)
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SettingsUpdate PUT /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings
func (rc *NodesClient) SettingsUpdate(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CommandGet GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute
func (rc *NodesClient) CommandGet(orgId string, deviceId string, nodeId string, commandName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"commandName": commandName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/commands/{commandName}/execute")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// JobsGet GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs/{jobId}
func (rc *NodesClient) JobsGet(orgId string, deviceId string, nodeId string, jobId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"jobId": jobId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/jobs/{jobId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// BulkCreate2 POST /orgs/{orgId}/devices/{deviceId}/nodes/bulk-create
func (rc *NodesClient) BulkCreate2(orgId string, deviceId string, allowUnknown bool, delete bool, start bool, parentId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("allowUnknown", strconv.FormatBool(allowUnknown))
	req.SetQueryParam("delete", strconv.FormatBool(delete))
	req.SetQueryParam("start", strconv.FormatBool(start))
	req.SetQueryParam("parentId", parentId)
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/bulk-create")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/nodes
func (rc *NodesClient) List(orgId string, deviceId string, type_ string, tags string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("type", type_)
	req.SetQueryParam("tags", tags)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SettingsSchemaByName GET /orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema/{schemaName}
func (rc *NodesClient) SettingsSchemaByName(orgId string, deviceId string, id string, schemaName string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		"schemaName": schemaName,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{id}/settings-schema/{schemaName}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

