// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs_search

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsSearchClient struct {
	c *client.Client
}

func NewDocsSearchClient(c *client.Client) *DocsSearchClient {
	return &DocsSearchClient{c: c}
}


// Search GET /orgs/{orgId}/devices/{deviceId}/docs/search
func (rc *DocsSearchClient) Search(orgId string, deviceId string, q string, scope string, collectionId string, rubixVersion string, limit int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("q", q)
	req.SetQueryParam("scope", scope)
	req.SetQueryParam("collectionId", collectionId)
	req.SetQueryParam("rubixVersion", rubixVersion)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/search")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

