// Code generated by rubix-sdk codegen. DO NOT EDIT.
package org_assets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type OrgAssetsClient struct {
	c *client.Client
}

func NewOrgAssetsClient(c *client.Client) *OrgAssetsClient {
	return &OrgAssetsClient{c: c}
}


// CreateDirectory POST /orgs/{orgId}/devices/{deviceId}/assets/org/directories
func (rc *OrgAssetsClient) CreateDirectory(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/directories")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Upload POST /orgs/{orgId}/devices/{deviceId}/assets/org/files
func (rc *OrgAssetsClient) Upload(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteFile DELETE /orgs/{orgId}/devices/{deviceId}/assets/org/files
func (rc *OrgAssetsClient) DeleteFile(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RenameFile PATCH /orgs/{orgId}/devices/{deviceId}/assets/org/files/rename
func (rc *OrgAssetsClient) RenameFile(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/files/rename")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetInfo GET /orgs/{orgId}/devices/{deviceId}/assets/org/info
func (rc *OrgAssetsClient) GetInfo(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/info")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/assets/org/browse
func (rc *OrgAssetsClient) List(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/browse")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteDirectory DELETE /orgs/{orgId}/devices/{deviceId}/assets/org/directories
func (rc *OrgAssetsClient) DeleteDirectory(orgId string, deviceId string, path string, recursive bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	req.SetQueryParam("recursive", strconv.FormatBool(recursive))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/directories")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RenameDirectory PATCH /orgs/{orgId}/devices/{deviceId}/assets/org/directories/rename
func (rc *OrgAssetsClient) RenameDirectory(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Patch(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/directories/rename")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Download GET /orgs/{orgId}/devices/{deviceId}/assets/org/files/download
func (rc *OrgAssetsClient) Download(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/assets/org/files/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

