// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: nats/v1/envelope.proto

package nats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wraps ALL request/reply NATS messages (used by bootstrap, queries, admin)
type NATSEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // "POST", "GET", "PUT", "DELETE"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // "/api/v1/orgs/{orgId}/devices/{deviceId}/nodes"
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                            // Serialized proto message (ProcessRequest, etc.)
	BodyType      string                 `protobuf:"bytes,5,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`    // "rubix.plugin.v1.ProcessRequest"
	Encoding      string                 `protobuf:"bytes,6,opt,name=encoding,proto3" json:"encoding,omitempty"`                    // "proto" (for future version detection)
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // For tracing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NATSEnvelope) Reset() {
	*x = NATSEnvelope{}
	mi := &file_nats_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NATSEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NATSEnvelope) ProtoMessage() {}

func (x *NATSEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_nats_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NATSEnvelope.ProtoReflect.Descriptor instead.
func (*NATSEnvelope) Descriptor() ([]byte, []int) {
	return file_nats_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *NATSEnvelope) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NATSEnvelope) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NATSEnvelope) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *NATSEnvelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NATSEnvelope) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

func (x *NATSEnvelope) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *NATSEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_nats_v1_envelope_proto protoreflect.FileDescriptor

const file_nats_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x16nats/v1/envelope.proto\x12\rrubix.nats.v1\"\xa2\x02\n" +
	"\fNATSEnvelope\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12?\n" +
	"\x06params\x18\x03 \x03(\v2'.rubix.nats.v1.NATSEnvelope.ParamsEntryR\x06params\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1b\n" +
	"\tbody_type\x18\x05 \x01(\tR\bbodyType\x12\x1a\n" +
	"\bencoding\x18\x06 \x01(\tR\bencoding\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B3Z1github.com/NubeIO/rubix-sdk/proto/go/nats/v1;natsb\x06proto3"

var (
	file_nats_v1_envelope_proto_rawDescOnce sync.Once
	file_nats_v1_envelope_proto_rawDescData []byte
)

func file_nats_v1_envelope_proto_rawDescGZIP() []byte {
	file_nats_v1_envelope_proto_rawDescOnce.Do(func() {
		file_nats_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_v1_envelope_proto_rawDesc), len(file_nats_v1_envelope_proto_rawDesc)))
	})
	return file_nats_v1_envelope_proto_rawDescData
}

var file_nats_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nats_v1_envelope_proto_goTypes = []any{
	(*NATSEnvelope)(nil), // 0: rubix.nats.v1.NATSEnvelope
	nil,                  // 1: rubix.nats.v1.NATSEnvelope.ParamsEntry
}
var file_nats_v1_envelope_proto_depIdxs = []int32{
	1, // 0: rubix.nats.v1.NATSEnvelope.params:type_name -> rubix.nats.v1.NATSEnvelope.ParamsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nats_v1_envelope_proto_init() }
func file_nats_v1_envelope_proto_init() {
	if File_nats_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_v1_envelope_proto_rawDesc), len(file_nats_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nats_v1_envelope_proto_goTypes,
		DependencyIndexes: file_nats_v1_envelope_proto_depIdxs,
		MessageInfos:      file_nats_v1_envelope_proto_msgTypes,
	}.Build()
	File_nats_v1_envelope_proto = out.File
	file_nats_v1_envelope_proto_goTypes = nil
	file_nats_v1_envelope_proto_depIdxs = nil
}
