// Code generated by rubix-sdk codegen. DO NOT EDIT.
package templates_usage

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TemplatesUsageClient struct {
	c *client.Client
}

func NewTemplatesUsageClient(c *client.Client) *TemplatesUsageClient {
	return &TemplatesUsageClient{c: c}
}


// Get GET /orgs/{orgId}/devices/{deviceId}/templates/{templateId}/usage
func (rc *TemplatesUsageClient) Get(orgId string, deviceId string, templateId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"templateId": templateId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{templateId}/usage")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

