// Code generated by rubix-sdk codegen. DO NOT EDIT.
package plugindata

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PlugindataClient struct {
	c *client.Client
}

func NewPlugindataClient(c *client.Client) *PlugindataClient {
	return &PlugindataClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}
func (rc *PlugindataClient) List(orgId string, deviceId string, pluginId string, table string, filter_field string, orderBy string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"table": table,
		
	})
	

	// Set query params
	req.SetQueryParam("filter[field]", filter_field)
	req.SetQueryParam("orderBy", orderBy)
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Insert POST /orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}
func (rc *PlugindataClient) Insert(orgId string, deviceId string, pluginId string, table string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"table": table,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/{id}
func (rc *PlugindataClient) Update(orgId string, deviceId string, pluginId string, table string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"table": table,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/{id}
func (rc *PlugindataClient) Delete(orgId string, deviceId string, pluginId string, table string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"table": table,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Aggregate POST /orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/aggregate
func (rc *PlugindataClient) Aggregate(orgId string, deviceId string, pluginId string, table string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"pluginId": pluginId,
		"table": table,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/plugindata/{pluginId}/{table}/aggregate")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

