// Code generated by rubix-sdk codegen. DO NOT EDIT.
package ras

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type RasClient struct {
	c *client.Client
}

func NewRasClient(c *client.Client) *RasClient {
	return &RasClient{c: c}
}


// GetFile GET /ras/file
func (rc *RasClient) GetFile(name string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	req.SetQueryParam("name", name)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/ras/file")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListFiles GET /ras/files
func (rc *RasClient) ListFiles(opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/ras/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

