// Code generated by rubix-sdk codegen. DO NOT EDIT.
package ping

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PingClient struct {
	c *client.Client
}

func NewPingClient(c *client.Client) *PingClient {
	return &PingClient{c: c}
}


// Status GET /orgs/{orgId}/devices/{deviceId}/ping
func (rc *PingClient) Status(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ping")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

