// Code generated by rubix-sdk codegen. DO NOT EDIT.
package templates_widgets_attach

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TemplatesWidgetsAttachClient struct {
	c *client.Client
}

func NewTemplatesWidgetsAttachClient(c *client.Client) *TemplatesWidgetsAttachClient {
	return &TemplatesWidgetsAttachClient{c: c}
}


// Attach POST /orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/attach
func (rc *TemplatesWidgetsAttachClient) Attach(orgId string, deviceId string, templateId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"templateId": templateId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/attach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Detach DELETE /orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/detach
func (rc *TemplatesWidgetsAttachClient) Detach(orgId string, deviceId string, templateId string, widgetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"templateId": templateId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/detach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets
func (rc *TemplatesWidgetsAttachClient) List(orgId string, deviceId string, templateId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"templateId": templateId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Reorder PUT /orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/reorder
func (rc *TemplatesWidgetsAttachClient) Reorder(orgId string, deviceId string, templateId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"templateId": templateId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{templateId}/widgets/{widgetId}/reorder")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

