// Code generated by rubix-sdk codegen. DO NOT EDIT.
package runtime

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type RuntimeClient struct {
	c *client.Client
}

func NewRuntimeClient(c *client.Client) *RuntimeClient {
	return &RuntimeClient{c: c}
}


// NodeLoadStatus GET /orgs/{orgId}/devices/{deviceId}/runtime/node-load-status
func (rc *RuntimeClient) NodeLoadStatus(orgId string, deviceId string, filter string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("filter", filter)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/node-load-status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetAllValues GET /orgs/{orgId}/devices/{deviceId}/runtime/values
func (rc *RuntimeClient) GetAllValues(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/values")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Snapshot GET /orgs/{orgId}/devices/{deviceId}/runtime/snapshot
func (rc *RuntimeClient) Snapshot(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/snapshot")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SnapshotHierarchical GET /orgs/{orgId}/devices/{deviceId}/runtime/snapshot/hierarchical
func (rc *RuntimeClient) SnapshotHierarchical(orgId string, deviceId string, parentId string, includeOrphans bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("parentId", parentId)
	req.SetQueryParam("includeOrphans", strconv.FormatBool(includeOrphans))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/snapshot/hierarchical")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetValuesScoped POST /orgs/{orgId}/devices/{deviceId}/runtime/values/scoped
func (rc *RuntimeClient) GetValuesScoped(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/values/scoped")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PalletList GET /orgs/{orgId}/devices/{deviceId}/runtime/pallet
func (rc *RuntimeClient) PalletList(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/pallet")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PalletRead GET /orgs/{orgId}/devices/{deviceId}/runtime/pallet/file
func (rc *RuntimeClient) PalletRead(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/pallet/file")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Start POST /orgs/{orgId}/devices/{deviceId}/runtime/start
func (rc *RuntimeClient) Start(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/start")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Stop POST /orgs/{orgId}/devices/{deviceId}/runtime/stop
func (rc *RuntimeClient) Stop(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/stop")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Status GET /orgs/{orgId}/devices/{deviceId}/runtime/status
func (rc *RuntimeClient) Status(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Restart POST /orgs/{orgId}/devices/{deviceId}/runtime/restart
func (rc *RuntimeClient) Restart(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/restart")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetNodeValues GET /orgs/{orgId}/devices/{deviceId}/runtime/nodes/{nodeId}/values
func (rc *RuntimeClient) GetNodeValues(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/nodes/{nodeId}/values")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// PalletExport POST /orgs/{orgId}/devices/{deviceId}/runtime/pallet/export
func (rc *RuntimeClient) PalletExport(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/runtime/pallet/export")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

