// Code generated by rubix-sdk codegen. DO NOT EDIT.
package nodes_assets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type NodesAssetsClient struct {
	c *client.Client
}

func NewNodesAssetsClient(c *client.Client) *NodesAssetsClient {
	return &NodesAssetsClient{c: c}
}


// ListAll GET /orgs/{orgId}/devices/{deviceId}/nodes/assets/list-all
func (rc *NodesAssetsClient) ListAll(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/assets/list-all")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/browse
func (rc *NodesAssetsClient) List(orgId string, deviceId string, nodeId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/browse")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Upload POST /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files
func (rc *NodesAssetsClient) Upload(orgId string, deviceId string, nodeId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Download GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files/download
func (rc *NodesAssetsClient) Download(orgId string, deviceId string, nodeId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files/download")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteFile DELETE /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files
func (rc *NodesAssetsClient) DeleteFile(orgId string, deviceId string, nodeId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/assets/files")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

