// Code generated by rubix-sdk codegen. DO NOT EDIT.
package templates

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TemplatesClient struct {
	c *client.Client
}

func NewTemplatesClient(c *client.Client) *TemplatesClient {
	return &TemplatesClient{c: c}
}


// Create POST /orgs/{orgId}/devices/{deviceId}/templates
func (rc *TemplatesClient) Create(orgId string, deviceId string, allowUnknown bool, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("allowUnknown", strconv.FormatBool(allowUnknown))
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/templates/{id}
func (rc *TemplatesClient) Update(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/templates/{id}
func (rc *TemplatesClient) Delete(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Resolve POST /orgs/{orgId}/devices/{deviceId}/templates/{id}/resolve
func (rc *TemplatesClient) Resolve(orgId string, deviceId string, id string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{id}/resolve")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/templates
func (rc *TemplatesClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/templates/{id}
func (rc *TemplatesClient) Get(orgId string, deviceId string, id string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"id": id,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/templates/{id}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

