// Code generated by rubix-sdk codegen. DO NOT EDIT.
package docs_versions

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type DocsVersionsClient struct {
	c *client.Client
}

func NewDocsVersionsClient(c *client.Client) *DocsVersionsClient {
	return &DocsVersionsClient{c: c}
}


// List GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions
func (rc *DocsVersionsClient) List(orgId string, deviceId string, collectionId string, docId string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions/{version}
func (rc *DocsVersionsClient) Get(orgId string, deviceId string, collectionId string, docId string, version string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		"version": version,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions/{version}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Restore POST /orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions/{version}/restore
func (rc *DocsVersionsClient) Restore(orgId string, deviceId string, collectionId string, docId string, version string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"collectionId": collectionId,
		"docId": docId,
		"version": version,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/docs/collections/{collectionId}/docs/{docId}/versions/{version}/restore")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

