// Code generated by rubix-sdk codegen. DO NOT EDIT.
package journal

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type JournalClient struct {
	c *client.Client
}

func NewJournalClient(c *client.Client) *JournalClient {
	return &JournalClient{c: c}
}


// Undo POST /orgs/{orgId}/devices/{deviceId}/journal/undo
func (rc *JournalClient) Undo(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/journal/undo")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Redo POST /orgs/{orgId}/devices/{deviceId}/journal/redo
func (rc *JournalClient) Redo(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/journal/redo")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// History GET /orgs/{orgId}/devices/{deviceId}/journal/history
func (rc *JournalClient) History(orgId string, deviceId string, limit int, offset int, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("limit", strconv.Itoa(limit))
	req.SetQueryParam("offset", strconv.Itoa(offset))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/journal/history")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UndoToTransaction POST /orgs/{orgId}/devices/{deviceId}/journal/undo/{txid}
func (rc *JournalClient) UndoToTransaction(orgId string, deviceId string, txid string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"txid": txid,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/journal/undo/{txid}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetTransaction GET /orgs/{orgId}/devices/{deviceId}/journal/transactions/{txid}
func (rc *JournalClient) GetTransaction(orgId string, deviceId string, txid string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"txid": txid,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/journal/transactions/{txid}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

