// Code generated by rubix-sdk codegen. DO NOT EDIT.
package tabs_widgets_attach

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TabsWidgetsAttachClient struct {
	c *client.Client
}

func NewTabsWidgetsAttachClient(c *client.Client) *TabsWidgetsAttachClient {
	return &TabsWidgetsAttachClient{c: c}
}


// Attach POST /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets/{widgetId}/attach
func (rc *TabsWidgetsAttachClient) Attach(orgId string, deviceId string, tabId string, widgetId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets/{widgetId}/attach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Detach DELETE /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets/{widgetId}/detach
func (rc *TabsWidgetsAttachClient) Detach(orgId string, deviceId string, tabId string, widgetId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		"widgetId": widgetId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets/{widgetId}/detach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets
func (rc *TabsWidgetsAttachClient) List(orgId string, deviceId string, tabId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/widgets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

