// Code generated by rubix-sdk codegen. DO NOT EDIT.
package teams

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TeamsClient struct {
	c *client.Client
}

func NewTeamsClient(c *client.Client) *TeamsClient {
	return &TeamsClient{c: c}
}


// AssignNav POST /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav/{navId}
func (rc *TeamsClient) AssignNav(orgId string, deviceId string, teamId string, navId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		"navId": navId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav/{navId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UnassignNav DELETE /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav
func (rc *TeamsClient) UnassignNav(orgId string, deviceId string, teamId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Update PUT /orgs/{orgId}/devices/{deviceId}/teams/{teamId}
func (rc *TeamsClient) Update(orgId string, deviceId string, teamId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// AddUser POST /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users/{userId}
func (rc *TeamsClient) AddUser(orgId string, deviceId string, teamId string, userId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		"userId": userId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users/{userId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// RemoveUser DELETE /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users/{userId}
func (rc *TeamsClient) RemoveUser(orgId string, deviceId string, teamId string, userId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		"userId": userId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users/{userId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetNav GET /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav
func (rc *TeamsClient) GetNav(orgId string, deviceId string, teamId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/nav")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/teams
func (rc *TeamsClient) List(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Create POST /orgs/{orgId}/devices/{deviceId}/teams
func (rc *TeamsClient) Create(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Get GET /orgs/{orgId}/devices/{deviceId}/teams/{teamId}
func (rc *TeamsClient) Get(orgId string, deviceId string, teamId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Delete DELETE /orgs/{orgId}/devices/{deviceId}/teams/{teamId}
func (rc *TeamsClient) Delete(orgId string, deviceId string, teamId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListUsers GET /orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users
func (rc *TeamsClient) ListUsers(orgId string, deviceId string, teamId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"teamId": teamId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/teams/{teamId}/users")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

