// Code generated by rubix-sdk codegen. DO NOT EDIT.
package tabs_templates_attach

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type TabsTemplatesAttachClient struct {
	c *client.Client
}

func NewTabsTemplatesAttachClient(c *client.Client) *TabsTemplatesAttachClient {
	return &TabsTemplatesAttachClient{c: c}
}


// Attach POST /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates/{templateId}/attach
func (rc *TabsTemplatesAttachClient) Attach(orgId string, deviceId string, tabId string, templateId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		"templateId": templateId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates/{templateId}/attach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Detach DELETE /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates/{templateId}/detach
func (rc *TabsTemplatesAttachClient) Detach(orgId string, deviceId string, tabId string, templateId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		"templateId": templateId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates/{templateId}/detach")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// List GET /orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates
func (rc *TabsTemplatesAttachClient) List(orgId string, deviceId string, tabId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"tabId": tabId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/tabs/{tabId}/templates")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

