// Code generated by rubix-sdk codegen. DO NOT EDIT.
package ports

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type PortsClient struct {
	c *client.Client
}

func NewPortsClient(c *client.Client) *PortsClient {
	return &PortsClient{c: c}
}


// Enable POST /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/enable
func (rc *PortsClient) Enable(orgId string, deviceId string, nodeId string, portHandle string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/enable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UpdateFacets PUT /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/facets
func (rc *PortsClient) UpdateFacets(orgId string, deviceId string, nodeId string, portHandle string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Put(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/facets")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListWithStatus GET /orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports-with-status
func (rc *PortsClient) ListWithStatus(orgId string, deviceId string, nodeId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/nodes/{nodeId}/ports-with-status")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// SetOverride POST /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override
func (rc *PortsClient) SetOverride(orgId string, deviceId string, nodeId string, portHandle string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ClearOverride DELETE /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override
func (rc *PortsClient) ClearOverride(orgId string, deviceId string, nodeId string, portHandle string, cancelJob bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	req.SetQueryParam("cancelJob", strconv.FormatBool(cancelJob))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetOverrideStatus GET /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override
func (rc *PortsClient) GetOverrideStatus(orgId string, deviceId string, nodeId string, portHandle string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// CancelTimeout DELETE /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override/timeout
func (rc *PortsClient) CancelTimeout(orgId string, deviceId string, nodeId string, portHandle string, clearOverride bool, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	req.SetQueryParam("clearOverride", strconv.FormatBool(clearOverride))
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/override/timeout")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// Disable POST /orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/disable
func (rc *PortsClient) Disable(orgId string, deviceId string, nodeId string, portHandle string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		"nodeId": nodeId,
		"portHandle": portHandle,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/ports/{nodeId}/{portHandle}/disable")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

