// Code generated by rubix-sdk codegen. DO NOT EDIT.
package riot_assets

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type RiotAssetsClient struct {
	c *client.Client
}

func NewRiotAssetsClient(c *client.Client) *RiotAssetsClient {
	return &RiotAssetsClient{c: c}
}


// ListPackages GET /orgs/{orgId}/devices/{deviceId}/riot/packages
func (rc *RiotAssetsClient) ListPackages(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/packages")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UploadPackage POST /orgs/{orgId}/devices/{deviceId}/riot/packages
func (rc *RiotAssetsClient) UploadPackage(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/packages")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeletePackage DELETE /orgs/{orgId}/devices/{deviceId}/riot/packages
func (rc *RiotAssetsClient) DeletePackage(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/packages")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// ListIoCards GET /orgs/{orgId}/devices/{deviceId}/riot/io-cards
func (rc *RiotAssetsClient) ListIoCards(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/io-cards")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// UploadIoCard POST /orgs/{orgId}/devices/{deviceId}/riot/io-cards
func (rc *RiotAssetsClient) UploadIoCard(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/io-cards")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// DeleteIoCard DELETE /orgs/{orgId}/devices/{deviceId}/riot/io-cards
func (rc *RiotAssetsClient) DeleteIoCard(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/riot/io-cards")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

