// Code generated by rubix-sdk codegen. DO NOT EDIT.
package host

import (
	"fmt"
	"strconv"

	"github.com/NubeIO/rubix-sdk/pkg/rubixclient/client"
)

var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

type HostClient struct {
	c *client.Client
}

func NewHostClient(c *client.Client) *HostClient {
	return &HostClient{c: c}
}


// GetInterfaces GET /orgs/{orgId}/devices/{deviceId}/host/interfaces
func (rc *HostClient) GetInterfaces(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/interfaces")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileRead GET /orgs/{orgId}/devices/{deviceId}/host/files/read
func (rc *HostClient) FileRead(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/read")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileDelete DELETE /orgs/{orgId}/devices/{deviceId}/host/files/delete
func (rc *HostClient) FileDelete(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Delete(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/delete")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileCopy POST /orgs/{orgId}/devices/{deviceId}/host/files/copy
func (rc *HostClient) FileCopy(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/copy")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileZip POST /orgs/{orgId}/devices/{deviceId}/host/files/zip
func (rc *HostClient) FileZip(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/zip")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileListZip GET /orgs/{orgId}/devices/{deviceId}/host/files/list-zip
func (rc *HostClient) FileListZip(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/list-zip")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetIp GET /orgs/{orgId}/devices/{deviceId}/host/ip
func (rc *HostClient) GetIp(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/ip")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileExists GET /orgs/{orgId}/devices/{deviceId}/host/files/exists
func (rc *HostClient) FileExists(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/exists")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileMove POST /orgs/{orgId}/devices/{deviceId}/host/files/move
func (rc *HostClient) FileMove(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/move")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileUnzip POST /orgs/{orgId}/devices/{deviceId}/host/files/unzip
func (rc *HostClient) FileUnzip(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/unzip")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetInfo GET /orgs/{orgId}/devices/{deviceId}/host
func (rc *HostClient) GetInfo(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileWrite POST /orgs/{orgId}/devices/{deviceId}/host/files/write
func (rc *HostClient) FileWrite(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/write")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileMkdir POST /orgs/{orgId}/devices/{deviceId}/host/files/mkdir
func (rc *HostClient) FileMkdir(orgId string, deviceId string, body interface{}, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	req.SetBody(body)
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Post(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/mkdir")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// GetTime GET /orgs/{orgId}/devices/{deviceId}/host/time
func (rc *HostClient) GetTime(orgId string, deviceId string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/time")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

// FileList GET /orgs/{orgId}/devices/{deviceId}/host/files/list
func (rc *HostClient) FileList(orgId string, deviceId string, path string, opts ...client.Option) (interface{}, error) {
	req := rc.c.R.R()

	// Set path params
	req.SetPathParams(map[string]string{
		"orgId": orgId,
		"deviceId": deviceId,
		
	})
	

	// Set query params
	req.SetQueryParam("path", path)
	

	// Set body if present
	

	// Apply options
	for _, opt := range opts {
		opt(req)
	}

	// Execute request
	resp, err := req.Get(rc.c.Prefix + "/orgs/{orgId}/devices/{deviceId}/host/files/list")
	if err != nil {
		return nil, err
	}

	return resp.Body(), nil
}

